//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#include "wxcrafter.h"


// Declare the bitmap loading function
extern void wxC9ED9InitBitmapResources();

static bool bBitmapLoaded = false;


MainFrameBaseClass::MainFrameBaseClass(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos, const wxSize& size, long style)
    : wxFrame(parent, id, title, pos, size, style)
{
    if ( !bBitmapLoaded ) {
        // We need to initialise the default bitmap handler
        wxXmlResource::Get()->AddHandler(new wxBitmapXmlHandler);
        wxC9ED9InitBitmapResources();
        bBitmapLoaded = true;
    }
    
    m_menuBar = new wxMenuBar(0);
    this->SetMenuBar(m_menuBar);
    
    m_name6 = new wxMenu();
    m_menuBar->Append(m_name6, _("File"));
    
    m_menuItem7 = new wxMenuItem(m_name6, wxID_EXIT, _("Exit\tAlt-X"), _("Quit"), wxITEM_NORMAL);
    m_name6->Append(m_menuItem7);
    
    m_name8 = new wxMenu();
    m_menuBar->Append(m_name8, _("Help"));
    
    m_menuItem9 = new wxMenuItem(m_name8, wxID_ABOUT, _("About..."), wxT(""), wxITEM_NORMAL);
    m_name8->Append(m_menuItem9);
    
    wxFlexGridSizer* flexGridSizer25 = new wxFlexGridSizer(1, 2, 0, 0);
    flexGridSizer25->SetFlexibleDirection( wxBOTH );
    flexGridSizer25->SetNonFlexibleGrowMode( wxFLEX_GROWMODE_SPECIFIED );
    flexGridSizer25->AddGrowableCol(1);
    flexGridSizer25->AddGrowableRow(0);
    this->SetSizer(flexGridSizer25);
    
    wxBoxSizer* boxSizer47 = new wxBoxSizer(wxVERTICAL);
    
    flexGridSizer25->Add(boxSizer47, 1, wxALL|wxEXPAND, 5);
    
    m_filePicker49 = new wxFilePickerCtrl(this, wxID_ANY, wxEmptyString, _("Select Landstalker ROM"), wxT("*.bin"), wxDefaultPosition, wxSize(-1,-1), wxFLP_DEFAULT_STYLE|wxFLP_SMALL);
    
    boxSizer47->Add(m_filePicker49, 0, wxALL, 5);
    
    wxArrayString m_choice53Arr;
    m_choice53 = new wxChoice(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), m_choice53Arr, 0);
    
    boxSizer47->Add(m_choice53, 0, wxALL, 5);
    
    m_button41 = new wxButton(this, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer47->Add(m_button41, 0, wxALL, 5);
    
    m_button51 = new wxButton(this, wxID_ANY, _("My Button"), wxDefaultPosition, wxSize(-1,-1), 0);
    
    boxSizer47->Add(m_button51, 0, wxALL, 5);
    
    m_scrollWin27 = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxSize(-1,-1), wxFULL_REPAINT_ON_RESIZE|wxALWAYS_SHOW_SB|wxHSCROLL|wxVSCROLL);
    m_scrollWin27->SetBackgroundColour(wxColour(wxT("rgb(0,0,0)")));
    m_scrollWin27->SetScrollRate(5, 5);
    
    flexGridSizer25->Add(m_scrollWin27, 100, wxEXPAND|wxRESERVE_SPACE_EVEN_IF_HIDDEN, 5);
    m_scrollWin27->SetMinSize(wxSize(150,100));
    
    m_statusBar29 = new wxStatusBar(this, wxID_ANY, wxSTB_DEFAULT_STYLE);
    m_statusBar29->SetFieldsCount(1);
    this->SetStatusBar(m_statusBar29);
    
    SetName(wxT("MainFrameBaseClass"));
    SetSize(800,600);
    if (GetSizer()) {
         GetSizer()->Fit(this);
    }
    if(GetParent()) {
        CentreOnParent(wxBOTH);
    } else {
        CentreOnScreen(wxBOTH);
    }
#if wxVERSION_NUMBER >= 2900
    if(!wxPersistenceManager::Get().Find(this)) {
        wxPersistenceManager::Get().RegisterAndRestore(this);
    } else {
        wxPersistenceManager::Get().Restore(this);
    }
#endif
    // Connect events
    this->Connect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Connect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    m_button41->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnButton41ButtonClicked), NULL, this);
    m_button51->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnButton51ButtonClicked), NULL, this);
    m_scrollWin27->Connect(wxEVT_PAINT, wxPaintEventHandler(MainFrameBaseClass::OnScrollwin27Paint), NULL, this);
    
}

MainFrameBaseClass::~MainFrameBaseClass()
{
    this->Disconnect(m_menuItem7->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnExit), NULL, this);
    this->Disconnect(m_menuItem9->GetId(), wxEVT_COMMAND_MENU_SELECTED, wxCommandEventHandler(MainFrameBaseClass::OnAbout), NULL, this);
    m_button41->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnButton41ButtonClicked), NULL, this);
    m_button51->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MainFrameBaseClass::OnButton51ButtonClicked), NULL, this);
    m_scrollWin27->Disconnect(wxEVT_PAINT, wxPaintEventHandler(MainFrameBaseClass::OnScrollwin27Paint), NULL, this);
    
}
