#include <landstalker/misc/include/DefaultLabels.h>

static const std::wstring C_ROOMS(L"rooms");
static const std::wstring C_BGMS(L"bgms");
static const std::wstring C_SOUNDS(L"sounds");
static const std::wstring C_ENTITIES(L"entities");

namespace DefaultLabels
{
	const std::map<std::pair<std::wstring, int>, std::wstring> DEFAULT_LABELS
	{
        {{C_ROOMS,     0},     L"000 Swamp shrine, floor 1"            },
        {{C_ROOMS,     1},     L"001 Swamp shrine, floor 1"            },
        {{C_ROOMS,     2},     L"002 Swamp shrine, floor 1"            },
        {{C_ROOMS,     3},     L"003 Swamp shrine, floor 1, stairs to floor 2"},
        {{C_ROOMS,     4},     L"004 Swamp shrine, floor 1"            },
        {{C_ROOMS,     5},     L"005 Swamp shrine, floor 1, boulders"  },
        {{C_ROOMS,     6},     L"006 Swamp shrine, floor 1"            },
        {{C_ROOMS,     7},     L"007 Swamp shrine, floor 1"            },
        {{C_ROOMS,     8},     L"008 Swamp shrine"                     },
        {{C_ROOMS,     9},     L"009 Swamp shrine"                     },
        {{C_ROOMS,     10},    L"010 Swamp shrine"                     },
        {{C_ROOMS,     11},    L"011 Swamp shrine"                     },
        {{C_ROOMS,     12},    L"012 Swamp shrine"                     },
        {{C_ROOMS,     13},    L"013 Swamp shrine"                     },
        {{C_ROOMS,     14},    L"014 Swamp shrine, floor 3"            },
        {{C_ROOMS,     15},    L"015 Swamp shrine, floor 1, boulders, empty"},
        {{C_ROOMS,     16},    L"016 Swamp shrine, floor 2, spiked boulders"},
        {{C_ROOMS,     17},    L"017 Swamp shrine, floor 2"            },
        {{C_ROOMS,     18},    L"018 Swamp shrine, floor 2, stairs to floor 3"},
        {{C_ROOMS,     19},    L"019 Swamp shrine"                     },
        {{C_ROOMS,     20},    L"020 Swamp shrine"                     },
        {{C_ROOMS,     21},    L"021 Swamp shrine, floor 3, spiked floor"},
        {{C_ROOMS,     22},    L"022 Swamp shrine"                     },
        {{C_ROOMS,     23},    L"023 Swamp shrine"                     },
        {{C_ROOMS,     24},    L"024 Swamp shrine"                     },
        {{C_ROOMS,     25},    L"025 Swamp shrine"                     },
        {{C_ROOMS,     26},    L"026 Swamp shrine"                     },
        {{C_ROOMS,     27},    L"027 Swamp shrine"                     },
        {{C_ROOMS,     28},    L"028 Swamp shrine"                     },
        {{C_ROOMS,     29},    L"029 Swamp shrine"                     },
        {{C_ROOMS,     30},    L"030 Swamp shrine"                     },
        {{C_ROOMS,     31},    L"031 Mercator castle ouside, main entrance"},
        {{C_ROOMS,     32},    L"032 Mercator castle, outside"         },
        {{C_ROOMS,     33},    L"033 Mercator castle, outside, west"   },
        {{C_ROOMS,     34},    L"034 Mercator castle, outside, west tower middle"},
        {{C_ROOMS,     35},    L"035 Mercator castle, outside, west tower top"},
        {{C_ROOMS,     36},    L"036 Mercator castle, basement entrance"},
        {{C_ROOMS,     37},    L"037 Mercator castle basement"         },
        {{C_ROOMS,     38},    L"038 Mercator castle basement"         },
        {{C_ROOMS,     39},    L"039 Mercator castle basement"         },
        {{C_ROOMS,     40},    L"040 Mercator castle basement"         },
        {{C_ROOMS,     41},    L"041 Mercator castle basement"         },
        {{C_ROOMS,     42},    L"042 Mercator castle basement"         },
        {{C_ROOMS,     43},    L"043 Mercator castle basement"         },
        {{C_ROOMS,     44},    L"044 Mercator castle basement, Moralis' cell"},
        {{C_ROOMS,     45},    L"045 Mercator castle basement, cell"   },
        {{C_ROOMS,     46},    L"046 Mercator castle basement"         },
        {{C_ROOMS,     47},    L"047 Mercator castle basement"         },
        {{C_ROOMS,     48},    L"048 Mercator castle basement"         },
        {{C_ROOMS,     49},    L"049 Mercator castle basement"         },
        {{C_ROOMS,     50},    L"050 Mercator castle basement"         },
        {{C_ROOMS,     51},    L"051 Mercator castle, throne"          },
        {{C_ROOMS,     52},    L"052 Mercator castle, throne"          },
        {{C_ROOMS,     53},    L"053 Mercator castle, throne"          },
        {{C_ROOMS,     54},    L"054 Mercator castle, throne"          },
        {{C_ROOMS,     55},    L"055 Mercator castle"                  },
        {{C_ROOMS,     56},    L"056 Mercator castle"                  },
        {{C_ROOMS,     57},    L"057 Mercator castle"                  },
        {{C_ROOMS,     58},    L"058 Mercator castle"                  },
        {{C_ROOMS,     59},    L"059 Mercator castle"                  },
        {{C_ROOMS,     60},    L"060 Mercator castle, main hall"       },
        {{C_ROOMS,     61},    L"061 Mercator castle, main hall"       },
        {{C_ROOMS,     62},    L"062 Mercator castle, main hall"       },
        {{C_ROOMS,     63},    L"063 Mercator castle, guards quaters"  },
        {{C_ROOMS,     64},    L"064 Mercator castle, guards quaters under attack"},
        {{C_ROOMS,     65},    L"065 Mercator castle"                  },
        {{C_ROOMS,     66},    L"066 Mercator castle"                  },
        {{C_ROOMS,     67},    L"067 Mercator castle"                  },
        {{C_ROOMS,     68},    L"068 Mercator castle, kitchen"         },
        {{C_ROOMS,     69},    L"069 Mercator castle, kitchen"         },
        {{C_ROOMS,     70},    L"070 Mercator castle"                  },
        {{C_ROOMS,     71},    L"071 Mercator castle"                  },
        {{C_ROOMS,     72},    L"072 Mercator castle"                  },
        {{C_ROOMS,     73},    L"073 Mercator castle, basement entrance"},
        {{C_ROOMS,     74},    L"074 Mercator castle, library"         },
        {{C_ROOMS,     75},    L"075 Mercator castle, library"         },
        {{C_ROOMS,     76},    L"076 Mercator castle"                  },
        {{C_ROOMS,     77},    L"077 Mercator castle"                  },
        {{C_ROOMS,     78},    L"078 Mercator castle, guards quaters"  },
        {{C_ROOMS,     79},    L"079 Mercator castle, guards quaters under attack"},
        {{C_ROOMS,     80},    L"080 Mercator castle"                  },
        {{C_ROOMS,     81},    L"081 Mercator castle"                  },
        {{C_ROOMS,     82},    L"082 Mercator castle"                  },
        {{C_ROOMS,     83},    L"083 Mercator castle"                  },
        {{C_ROOMS,     84},    L"084 Mercator castle, guards quaters under attack"},
        {{C_ROOMS,     85},    L"085 Mercator castle, Banquet hall"    },
        {{C_ROOMS,     86},    L"086 Mercator castle"                  },
        {{C_ROOMS,     87},    L"087 Mercator castle"                  },
        {{C_ROOMS,     88},    L"088 Mercator castle"                  },
        {{C_ROOMS,     89},    L"089 Mercator castle"                  },
        {{C_ROOMS,     90},    L"090 Mercator castle, guards quaters under attack"},
        {{C_ROOMS,     91},    L"091 Mercator castle"                  },
        {{C_ROOMS,     92},    L"092 Mercator castle"                  },
        {{C_ROOMS,     93},    L"093 Mercator castle"                  },
        {{C_ROOMS,     94},    L"094 Mercator castle"                  },
        {{C_ROOMS,     95},    L"095 Mercator castle"                  },
        {{C_ROOMS,     96},    L"096 Mercator castle"                  },
        {{C_ROOMS,     97},    L"097 Mercator castle"                  },
        {{C_ROOMS,     98},    L"098 Mercator castle"                  },
        {{C_ROOMS,     99},    L"099 Mercator castle, room"            },
        {{C_ROOMS,     100},   L"100 Mercator castle, Bathroom (entrance)"},
        {{C_ROOMS,     101},   L"101 Mercator castle, Bathroom"        },
        {{C_ROOMS,     102},   L"102 Mercator castle, Bathroom (empty)"},
        {{C_ROOMS,     103},   L"103 Mercator castle"                  },
        {{C_ROOMS,     104},   L"104 Mercator castle"                  },
        {{C_ROOMS,     105},   L"105 Mercator castle"                  },
        {{C_ROOMS,     106},   L"106 Mercator castle"                  },
        {{C_ROOMS,     107},   L"107 Mercator castle"                  },
        {{C_ROOMS,     108},   L"108 Mercator castle"                  },
        {{C_ROOMS,     109},   L"109 Mercator castle"                  },
        {{C_ROOMS,     110},   L"110 Mercator castle"                  },
        {{C_ROOMS,     111},   L"111 Treasure room (Nole)"             },
        {{C_ROOMS,     112},   L"112 Treasure room (Gola)"             },
        {{C_ROOMS,     113},   L"113 Treasure room (empty)"            },
        {{C_ROOMS,     114},   L"114 Nole palace, pillars"             },
        {{C_ROOMS,     115},   L"115 Nole palace"                      },
        {{C_ROOMS,     116},   L"116 Nole palace"                      },
        {{C_ROOMS,     117},   L"117 Nole palace, save"                },
        {{C_ROOMS,     118},   L"118 Nole palace"                      },
        {{C_ROOMS,     119},   L"119 Nole palace, stone warrior"       },
        {{C_ROOMS,     120},   L"120 Nole palace"                      },
        {{C_ROOMS,     121},   L"121 Nole palace, spinner"             },
        {{C_ROOMS,     122},   L"122 Nole palace"                      },
        {{C_ROOMS,     123},   L"123 Nole palace"                      },
        {{C_ROOMS,     124},   L"124 Nole palace"                      },
        {{C_ROOMS,     125},   L"125 Nole palace"                      },
        {{C_ROOMS,     126},   L"126 Nole palace"                      },
        {{C_ROOMS,     127},   L"127 Nole palace"                      },
        {{C_ROOMS,     128},   L"128 Nole palace"                      },
        {{C_ROOMS,     129},   L"129 Nole palace"                      },
        {{C_ROOMS,     130},   L"130 Nole palace"                      },
        {{C_ROOMS,     131},   L"131 Nole palace"                      },
        {{C_ROOMS,     132},   L"132 Nole palace"                      },
        {{C_ROOMS,     133},   L"133 Nole palace"                      },
        {{C_ROOMS,     134},   L"134 Nole palace"                      },
        {{C_ROOMS,     135},   L"135 Nole palace"                      },
        {{C_ROOMS,     136},   L"136 Nole palace"                      },
        {{C_ROOMS,     137},   L"137 Nole palace"                      },
        {{C_ROOMS,     138},   L"138 Nole palace"                      },
        {{C_ROOMS,     139},   L"139 Jypta Ruins"                      },
        {{C_ROOMS,     140},   L"140 Jypta Ruins"                      },
        {{C_ROOMS,     141},   L"141 Jypta Ruins"                      },
        {{C_ROOMS,     142},   L"142 Kalva harbor"                     },
        {{C_ROOMS,     143},   L"143 Bird"                             },
        {{C_ROOMS,     144},   L"144 Nole cave"                        },
        {{C_ROOMS,     145},   L"145 Nole cave"                        },
        {{C_ROOMS,     146},   L"146 Nole cave"                        },
        {{C_ROOMS,     147},   L"147 Nole cave"                        },
        {{C_ROOMS,     148},   L"148 Nole cave, outside"               },
        {{C_ROOMS,     149},   L"149 Nole cave"                        },
        {{C_ROOMS,     150},   L"150 Nole cave"                        },
        {{C_ROOMS,     151},   L"151 Nole cave"                        },
        {{C_ROOMS,     152},   L"152 Nole cave"                        },
        {{C_ROOMS,     153},   L"153 Nole cave"                        },
        {{C_ROOMS,     154},   L"154 Nole cave"                        },
        {{C_ROOMS,     155},   L"155 Nole cave"                        },
        {{C_ROOMS,     156},   L"156 Nole cave"                        },
        {{C_ROOMS,     157},   L"157 Nole cave"                        },
        {{C_ROOMS,     158},   L"158 Nole cave"                        },
        {{C_ROOMS,     159},   L"159 Nole cave"                        },
        {{C_ROOMS,     160},   L"160 Nole cave"                        },
        {{C_ROOMS,     161},   L"161 Nole cave"                        },
        {{C_ROOMS,     162},   L"162 Nole cave"                        },
        {{C_ROOMS,     163},   L"163 Nole cave"                        },
        {{C_ROOMS,     164},   L"164 Nole cave"                        },
        {{C_ROOMS,     165},   L"165 Nole cave"                        },
        {{C_ROOMS,     166},   L"166 Nole cave"                        },
        {{C_ROOMS,     167},   L"167 Nole cave, river"                 },
        {{C_ROOMS,     168},   L"168 Nole cave, river"                 },
        {{C_ROOMS,     169},   L"169 Nole cave, river"                 },
        {{C_ROOMS,     170},   L"170 Nole cave"                        },
        {{C_ROOMS,     171},   L"171 Nole cave"                        },
        {{C_ROOMS,     172},   L"172 Nole cave"                        },
        {{C_ROOMS,     173},   L"173 Gemstone room"                    },
        {{C_ROOMS,     174},   L"174 Waterfall shrine"                 },
        {{C_ROOMS,     175},   L"175 Waterfall shrine"                 },
        {{C_ROOMS,     176},   L"176 Waterfall shrine"                 },
        {{C_ROOMS,     177},   L"177 Waterfall shrine"                 },
        {{C_ROOMS,     178},   L"178 Waterfall shrine"                 },
        {{C_ROOMS,     179},   L"179 Waterfall shrine"                 },
        {{C_ROOMS,     180},   L"180 Waterfall shrine"                 },
        {{C_ROOMS,     181},   L"181 Waterfall shrine"                 },
        {{C_ROOMS,     182},   L"182 Waterfall shrine"                 },
        {{C_ROOMS,     183},   L"183 Thieves' hideout (Outside entrance)"},
        {{C_ROOMS,     184},   L"184 Thieves' hideout"                 },
        {{C_ROOMS,     185},   L"185 Thieves' hideout"                 },
        {{C_ROOMS,     186},   L"186 Thieves' hideout"                 },
        {{C_ROOMS,     187},   L"187 Thieves' hideout"                 },
        {{C_ROOMS,     188},   L"188 Thieves' hideout"                 },
        {{C_ROOMS,     189},   L"189 Thieves' hideout"                 },
        {{C_ROOMS,     190},   L"190 Thieves' hideout"                 },
        {{C_ROOMS,     191},   L"191 Thieves' hideout, cell"           },
        {{C_ROOMS,     192},   L"192 Thieves' hideout"                 },
        {{C_ROOMS,     193},   L"193 Thieves' hideout"                 },
        {{C_ROOMS,     194},   L"194 Thieves' hideout"                 },
        {{C_ROOMS,     195},   L"195 Thieves' hideout"                 },
        {{C_ROOMS,     196},   L"196 Thieves' hideout"                 },
        {{C_ROOMS,     197},   L"197 Thieves' hideout"                 },
        {{C_ROOMS,     198},   L"198 Thieves' hideout"                 },
        {{C_ROOMS,     199},   L"199 Thieves' hideout"                 },
        {{C_ROOMS,     200},   L"200 Thieves' hideout"                 },
        {{C_ROOMS,     201},   L"201 Thieves' hideout"                 },
        {{C_ROOMS,     202},   L"202 Thieves' hideout"                 },
        {{C_ROOMS,     203},   L"203 Thieves' hideout"                 },
        {{C_ROOMS,     204},   L"204 Thieves' hideout"                 },
        {{C_ROOMS,     205},   L"205 Thieves' hideout"                 },
        {{C_ROOMS,     206},   L"206 Thieves' hideout"                 },
        {{C_ROOMS,     207},   L"207 Thieves' hideout"                 },
        {{C_ROOMS,     208},   L"208 Thieves' hideout"                 },
        {{C_ROOMS,     209},   L"209 Thieves' hideout"                 },
        {{C_ROOMS,     210},   L"210 Thieves' hideout"                 },
        {{C_ROOMS,     211},   L"211 Thieves' hideout"                 },
        {{C_ROOMS,     212},   L"212 Thieves' hideout"                 },
        {{C_ROOMS,     213},   L"213 Thieves' hideout"                 },
        {{C_ROOMS,     214},   L"214 Thieves' hideout"                 },
        {{C_ROOMS,     215},   L"215 Thieves' hideout"                 },
        {{C_ROOMS,     216},   L"216 Thieves' hideout"                 },
        {{C_ROOMS,     217},   L"217 Thieves' hideout"                 },
        {{C_ROOMS,     218},   L"218 Thieves' hideout"                 },
        {{C_ROOMS,     219},   L"219 Thieves' hideout, save"           },
        {{C_ROOMS,     220},   L"220 Thieves' hideout, save"           },
        {{C_ROOMS,     221},   L"221 Thieves' hideout"                 },
        {{C_ROOMS,     222},   L"222 Thieves' hideout"                 },
        {{C_ROOMS,     223},   L"223 Thieves' hideout"                 },
        {{C_ROOMS,     224},   L"224 Thieves' hideout"                 },
        {{C_ROOMS,     225},   L"225 Thieves' hideout"                 },
        {{C_ROOMS,     226},   L"226 Thieves' hideout, cliff"          },
        {{C_ROOMS,     227},   L"227 Verla Mine"                       },
        {{C_ROOMS,     228},   L"228 Verla Mine"                       },
        {{C_ROOMS,     229},   L"229 Verla Mine"                       },
        {{C_ROOMS,     230},   L"230 Verla Mine"                       },
        {{C_ROOMS,     231},   L"231 Verla Mine"                       },
        {{C_ROOMS,     232},   L"232 Verla Mine"                       },
        {{C_ROOMS,     233},   L"233 Verla Mine"                       },
        {{C_ROOMS,     234},   L"234 Verla Mine"                       },
        {{C_ROOMS,     235},   L"235 Verla Mine"                       },
        {{C_ROOMS,     236},   L"236 Verla Mine"                       },
        {{C_ROOMS,     237},   L"237 Verla Mine"                       },
        {{C_ROOMS,     238},   L"238 Verla Mine"                       },
        {{C_ROOMS,     239},   L"239 Verla Mine"                       },
        {{C_ROOMS,     240},   L"240 Verla Mine"                       },
        {{C_ROOMS,     241},   L"241 Verla Mine"                       },
        {{C_ROOMS,     242},   L"242 Verla Mine"                       },
        {{C_ROOMS,     243},   L"243 Verla Mine"                       },
        {{C_ROOMS,     244},   L"244 Verla Mine"                       },
        {{C_ROOMS,     245},   L"245 Verla Mine"                       },
        {{C_ROOMS,     246},   L"246 Verla Mine"                       },
        {{C_ROOMS,     247},   L"247 Verla Mine"                       },
        {{C_ROOMS,     248},   L"248 Verla Mine"                       },
        {{C_ROOMS,     249},   L"249 Verla Mine"                       },
        {{C_ROOMS,     250},   L"250 Verla Mine"                       },
        {{C_ROOMS,     251},   L"251 Verla Mine"                       },
        {{C_ROOMS,     252},   L"252 Verla Mine"                       },
        {{C_ROOMS,     253},   L"253 Verla Mine"                       },
        {{C_ROOMS,     254},   L"254 Verla Mine"                       },
        {{C_ROOMS,     255},   L"255 Verla Mine"                       },
        {{C_ROOMS,     256},   L"256 Verla Mine"                       },
        {{C_ROOMS,     257},   L"257 Verla Mine"                       },
        {{C_ROOMS,     258},   L"258 Verla Mine"                       },
        {{C_ROOMS,     259},   L"259 Verla Mine"                       },
        {{C_ROOMS,     260},   L"260 Verla Mine"                       },
        {{C_ROOMS,     261},   L"261 Verla Mine"                       },
        {{C_ROOMS,     262},   L"262 Verla Mine"                       },
        {{C_ROOMS,     263},   L"263 Verla Mine"                       },
        {{C_ROOMS,     264},   L"264 Verla Mine"                       },
        {{C_ROOMS,     265},   L"265 Verla Mine"                       },
        {{C_ROOMS,     266},   L"266 Verla Mine"                       },
        {{C_ROOMS,     267},   L"267 Verla Mine"                       },
        {{C_ROOMS,     268},   L"268 Verla Mine"                       },
        {{C_ROOMS,     269},   L"269 Verla Mine"                       },
        {{C_ROOMS,     270},   L"270 Destel well"                      },
        {{C_ROOMS,     271},   L"271 Destel well"                      },
        {{C_ROOMS,     272},   L"272 Destel well"                      },
        {{C_ROOMS,     273},   L"273 Destel well"                      },
        {{C_ROOMS,     274},   L"274 Destel well"                      },
        {{C_ROOMS,     275},   L"275 Destel well"                      },
        {{C_ROOMS,     276},   L"276 Destel well"                      },
        {{C_ROOMS,     277},   L"277 Destel well"                      },
        {{C_ROOMS,     278},   L"278 Destel well"                      },
        {{C_ROOMS,     279},   L"279 Destel well"                      },
        {{C_ROOMS,     280},   L"280 Destel well"                      },
        {{C_ROOMS,     281},   L"281 Destel well"                      },
        {{C_ROOMS,     282},   L"282 Destel well"                      },
        {{C_ROOMS,     283},   L"283 Destel well"                      },
        {{C_ROOMS,     284},   L"284 Destel well"                      },
        {{C_ROOMS,     285},   L"285 Destel well"                      },
        {{C_ROOMS,     286},   L"286 Destel well"                      },
        {{C_ROOMS,     287},   L"287 Destel well"                      },
        {{C_ROOMS,     288},   L"288 Destel well"                      },
        {{C_ROOMS,     289},   L"289 Destel well"                      },
        {{C_ROOMS,     290},   L"290 Destel well"                      },
        {{C_ROOMS,     291},   L"291 Lake Shrine"                      },
        {{C_ROOMS,     292},   L"292 Lake Shrine"                      },
        {{C_ROOMS,     293},   L"293 Lake Shrine"                      },
        {{C_ROOMS,     294},   L"294 Lake Shrine"                      },
        {{C_ROOMS,     295},   L"295 Lake Shrine"                      },
        {{C_ROOMS,     296},   L"296 Lake Shrine"                      },
        {{C_ROOMS,     297},   L"297 Lake Shrine"                      },
        {{C_ROOMS,     298},   L"298 Lake Shrine"                      },
        {{C_ROOMS,     299},   L"299 Lake Shrine"                      },
        {{C_ROOMS,     300},   L"300 Lake Shrine"                      },
        {{C_ROOMS,     301},   L"301 Lake Shrine"                      },
        {{C_ROOMS,     302},   L"302 Lake Shrine"                      },
        {{C_ROOMS,     303},   L"303 Lake Shrine"                      },
        {{C_ROOMS,     304},   L"304 Lake Shrine"                      },
        {{C_ROOMS,     305},   L"305 Lake Shrine"                      },
        {{C_ROOMS,     306},   L"306 Lake Shrine"                      },
        {{C_ROOMS,     307},   L"307 Lake Shrine"                      },
        {{C_ROOMS,     308},   L"308 Lake Shrine"                      },
        {{C_ROOMS,     309},   L"309 Lake Shrine"                      },
        {{C_ROOMS,     310},   L"310 Lake Shrine"                      },
        {{C_ROOMS,     311},   L"311 Lake Shrine"                      },
        {{C_ROOMS,     312},   L"312 Lake Shrine"                      },
        {{C_ROOMS,     313},   L"313 Lake Shrine"                      },
        {{C_ROOMS,     314},   L"314 Lake Shrine"                      },
        {{C_ROOMS,     315},   L"315 Lake Shrine"                      },
        {{C_ROOMS,     316},   L"316 Lake Shrine"                      },
        {{C_ROOMS,     317},   L"317 Lake Shrine"                      },
        {{C_ROOMS,     318},   L"318 Lake Shrine"                      },
        {{C_ROOMS,     319},   L"319 Lake Shrine"                      },
        {{C_ROOMS,     320},   L"320 Lake Shrine"                      },
        {{C_ROOMS,     321},   L"321 Lake Shrine"                      },
        {{C_ROOMS,     322},   L"322 Lake Shrine"                      },
        {{C_ROOMS,     323},   L"323 Lake Shrine"                      },
        {{C_ROOMS,     324},   L"324 Lake Shrine"                      },
        {{C_ROOMS,     325},   L"325 Lake Shrine"                      },
        {{C_ROOMS,     326},   L"326 Lake Shrine"                      },
        {{C_ROOMS,     327},   L"327 Lake Shrine"                      },
        {{C_ROOMS,     328},   L"328 Lake Shrine"                      },
        {{C_ROOMS,     329},   L"329 Lake Shrine"                      },
        {{C_ROOMS,     330},   L"330 Lake Shrine"                      },
        {{C_ROOMS,     331},   L"331 Lake Shrine"                      },
        {{C_ROOMS,     332},   L"332 Lake Shrine"                      },
        {{C_ROOMS,     333},   L"333 Lake Shrine"                      },
        {{C_ROOMS,     334},   L"334 Lake Shrine"                      },
        {{C_ROOMS,     335},   L"335 Lake Shrine"                      },
        {{C_ROOMS,     336},   L"336 Lake Shrine"                      },
        {{C_ROOMS,     337},   L"337 Lake Shrine"                      },
        {{C_ROOMS,     338},   L"338 Lake Shrine"                      },
        {{C_ROOMS,     339},   L"339 Lake Shrine"                      },
        {{C_ROOMS,     340},   L"340 Lake Shrine"                      },
        {{C_ROOMS,     341},   L"341 Lake Shrine"                      },
        {{C_ROOMS,     342},   L"342 Lake Shrine"                      },
        {{C_ROOMS,     343},   L"343 Lake Shrine"                      },
        {{C_ROOMS,     344},   L"344 Lake Shrine"                      },
        {{C_ROOMS,     345},   L"345 Lake Shrine"                      },
        {{C_ROOMS,     346},   L"346 Lake Shrine"                      },
        {{C_ROOMS,     347},   L"347 Lake Shrine"                      },
        {{C_ROOMS,     348},   L"348 Lake Shrine"                      },
        {{C_ROOMS,     349},   L"349 Lake Shrine"                      },
        {{C_ROOMS,     350},   L"350 Lake Shrine"                      },
        {{C_ROOMS,     351},   L"351 Lake Shrine"                      },
        {{C_ROOMS,     352},   L"352 Lake Shrine"                      },
        {{C_ROOMS,     353},   L"353 Lake Shrine"                      },
        {{C_ROOMS,     354},   L"354 Lake Shrine"                      },
        {{C_ROOMS,     355},   L"355 Nole's labyrinth"                 },
        {{C_ROOMS,     356},   L"356 Nole's labyrinth"                 },
        {{C_ROOMS,     357},   L"357 Nole's labyrinth"                 },
        {{C_ROOMS,     358},   L"358 Nole's labyrinth"                 },
        {{C_ROOMS,     359},   L"359 Nole's labyrinth"                 },
        {{C_ROOMS,     360},   L"360 Nole's labyrinth"                 },
        {{C_ROOMS,     361},   L"361 Nole's labyrinth"                 },
        {{C_ROOMS,     362},   L"362 Nole's labyrinth"                 },
        {{C_ROOMS,     363},   L"363 Nole's labyrinth"                 },
        {{C_ROOMS,     364},   L"364 Nole's labyrinth"                 },
        {{C_ROOMS,     365},   L"365 Nole's labyrinth"                 },
        {{C_ROOMS,     366},   L"366 Nole's labyrinth"                 },
        {{C_ROOMS,     367},   L"367 Nole's labyrinth"                 },
        {{C_ROOMS,     368},   L"368 Nole's labyrinth"                 },
        {{C_ROOMS,     369},   L"369 Nole's labyrinth"                 },
        {{C_ROOMS,     370},   L"370 Nole's labyrinth"                 },
        {{C_ROOMS,     371},   L"371 Nole's labyrinth"                 },
        {{C_ROOMS,     372},   L"372 Nole's labyrinth"                 },
        {{C_ROOMS,     373},   L"373 Nole's labyrinth"                 },
        {{C_ROOMS,     374},   L"374 Nole's labyrinth"                 },
        {{C_ROOMS,     375},   L"375 Nole's labyrinth"                 },
        {{C_ROOMS,     376},   L"376 Nole's labyrinth"                 },
        {{C_ROOMS,     377},   L"377 Nole's labyrinth"                 },
        {{C_ROOMS,     378},   L"378 Nole's labyrinth"                 },
        {{C_ROOMS,     379},   L"379 Nole's labyrinth"                 },
        {{C_ROOMS,     380},   L"380 Nole's labyrinth"                 },
        {{C_ROOMS,     381},   L"381 Nole's labyrinth"                 },
        {{C_ROOMS,     382},   L"382 Nole's labyrinth"                 },
        {{C_ROOMS,     383},   L"383 Nole's labyrinth"                 },
        {{C_ROOMS,     384},   L"384 Nole's labyrinth"                 },
        {{C_ROOMS,     385},   L"385 Nole's labyrinth"                 },
        {{C_ROOMS,     386},   L"386 Nole's labyrinth"                 },
        {{C_ROOMS,     387},   L"387 Nole's labyrinth"                 },
        {{C_ROOMS,     388},   L"388 Nole's labyrinth"                 },
        {{C_ROOMS,     389},   L"389 Nole's labyrinth"                 },
        {{C_ROOMS,     390},   L"390 Nole's labyrinth"                 },
        {{C_ROOMS,     391},   L"391 Nole's labyrinth"                 },
        {{C_ROOMS,     392},   L"392 Nole's labyrinth"                 },
        {{C_ROOMS,     393},   L"393 Nole's labyrinth"                 },
        {{C_ROOMS,     394},   L"394 Nole's labyrinth"                 },
        {{C_ROOMS,     395},   L"395 Nole's labyrinth"                 },
        {{C_ROOMS,     396},   L"396 Nole's labyrinth"                 },
        {{C_ROOMS,     397},   L"397 Nole's labyrinth"                 },
        {{C_ROOMS,     398},   L"398 Nole's labyrinth"                 },
        {{C_ROOMS,     399},   L"399 Nole's labyrinth"                 },
        {{C_ROOMS,     400},   L"400 Nole's labyrinth"                 },
        {{C_ROOMS,     401},   L"401 Nole's labyrinth"                 },
        {{C_ROOMS,     402},   L"402 Nole's labyrinth"                 },
        {{C_ROOMS,     403},   L"403 Nole's labyrinth"                 },
        {{C_ROOMS,     404},   L"404 Nole's labyrinth"                 },
        {{C_ROOMS,     405},   L"405 Nole's labyrinth"                 },
        {{C_ROOMS,     406},   L"406 Nole's labyrinth"                 },
        {{C_ROOMS,     407},   L"407 Nole's labyrinth"                 },
        {{C_ROOMS,     408},   L"408 Nole's labyrinth"                 },
        {{C_ROOMS,     409},   L"409 Nole's labyrinth"                 },
        {{C_ROOMS,     410},   L"410 Nole's labyrinth"                 },
        {{C_ROOMS,     411},   L"411 Nole's labyrinth"                 },
        {{C_ROOMS,     412},   L"412 Nole's labyrinth"                 },
        {{C_ROOMS,     413},   L"413 Nole's labyrinth"                 },
        {{C_ROOMS,     414},   L"414 Nole's labyrinth"                 },
        {{C_ROOMS,     415},   L"415 Nole's labyrinth"                 },
        {{C_ROOMS,     416},   L"416 Nole's labyrinth"                 },
        {{C_ROOMS,     417},   L"417 Nole's labyrinth"                 },
        {{C_ROOMS,     418},   L"418 Nole's labyrinth"                 },
        {{C_ROOMS,     419},   L"419 Nole's labyrinth"                 },
        {{C_ROOMS,     420},   L"420 Nole's labyrinth"                 },
        {{C_ROOMS,     421},   L"421 Nole palace, stairs"              },
        {{C_ROOMS,     422},   L"422 Nole's labyrinth"                 },
        {{C_ROOMS,     423},   L"423 Nole's labyrinth"                 },
        {{C_ROOMS,     424},   L"424 Road"                             },
        {{C_ROOMS,     425},   L"425 Road"                             },
        {{C_ROOMS,     426},   L"426 Road, ouside of waterfall shrine" },
        {{C_ROOMS,     427},   L"427 Road"                             },
        {{C_ROOMS,     428},   L"428 Road"                             },
        {{C_ROOMS,     429},   L"429 Cliff"                            },
        {{C_ROOMS,     430},   L"430 Cliff"                            },
        {{C_ROOMS,     431},   L"431 Swamp"                            },
        {{C_ROOMS,     432},   L"432 Swamp"                            },
        {{C_ROOMS,     433},   L"433 Swamp, shrine outside"            },
        {{C_ROOMS,     434},   L"434 Road"                             },
        {{C_ROOMS,     435},   L"435 Road"                             },
        {{C_ROOMS,     436},   L"436 Swamp"                            },
        {{C_ROOMS,     437},   L"437 Road"                             },
        {{C_ROOMS,     438},   L"438 Road"                             },
        {{C_ROOMS,     439},   L"439 Road"                             },
        {{C_ROOMS,     440},   L"440 Road"                             },
        {{C_ROOMS,     441},   L"441 Helga's hut, outside"             },
        {{C_ROOMS,     442},   L"442 Lone house"                       },
        {{C_ROOMS,     443},   L"443 Swamp"                            },
        {{C_ROOMS,     444},   L"444 Swamp"                            },
        {{C_ROOMS,     445},   L"445 Road"                             },
        {{C_ROOMS,     446},   L"446 Road"                             },
        {{C_ROOMS,     447},   L"447 Road"                             },
        {{C_ROOMS,     448},   L"448 Road"                             },
        {{C_ROOMS,     449},   L"449 Road"                             },
        {{C_ROOMS,     450},   L"450 Road"                             },
        {{C_ROOMS,     451},   L"451 Road"                             },
        {{C_ROOMS,     452},   L"452 Road"                             },
        {{C_ROOMS,     453},   L"453 Road"                             },
        {{C_ROOMS,     454},   L"454 Mercator gate"                    },
        {{C_ROOMS,     455},   L"455 Road"                             },
        {{C_ROOMS,     456},   L"456 Road"                             },
        {{C_ROOMS,     457},   L"457 Road"                             },
        {{C_ROOMS,     458},   L"458 Road"                             },
        {{C_ROOMS,     459},   L"459 Road"                             },
        {{C_ROOMS,     460},   L"460 Road"                             },
        {{C_ROOMS,     461},   L"461 Road, ouside of Friday's village" },
        {{C_ROOMS,     462},   L"462 Friday's village"                 },
        {{C_ROOMS,     463},   L"463 Road"                             },
        {{C_ROOMS,     464},   L"464 Road"                             },
        {{C_ROOMS,     465},   L"465 Road"                             },
        {{C_ROOMS,     466},   L"466 Underground passage"              },
        {{C_ROOMS,     467},   L"467 Road"                             },
        {{C_ROOMS,     468},   L"468 Road"                             },
        {{C_ROOMS,     469},   L"469 Road"                             },
        {{C_ROOMS,     470},   L"470 Road"                             },
        {{C_ROOMS,     471},   L"471 Underground passage"              },
        {{C_ROOMS,     472},   L"472 Road"                             },
        {{C_ROOMS,     473},   L"473 Road"                             },
        {{C_ROOMS,     474},   L"474 Road"                             },
        {{C_ROOMS,     475},   L"475 Mir tower, outside"               },
        {{C_ROOMS,     476},   L"476 Road"                             },
        {{C_ROOMS,     477},   L"477 Soldier's house"                  },
        {{C_ROOMS,     478},   L"478 Road, waterfall"                  },
        {{C_ROOMS,     479},   L"479 Helga's hut"                      },
        {{C_ROOMS,     480},   L"480 Helga's hut, entrance"            },
        {{C_ROOMS,     481},   L"481 Mountain"                         },
        {{C_ROOMS,     482},   L"482 Mountain"                         },
        {{C_ROOMS,     483},   L"483 Mountain"                         },
        {{C_ROOMS,     484},   L"484 Mountain"                         },
        {{C_ROOMS,     485},   L"485 Mountain"                         },
        {{C_ROOMS,     486},   L"486 Mountain, save"                   },
        {{C_ROOMS,     487},   L"487 Mountain"                         },
        {{C_ROOMS,     488},   L"488 Road, lake"                       },
        {{C_ROOMS,     489},   L"489 Road, hut"                        },
        {{C_ROOMS,     490},   L"490 Road"                             },
        {{C_ROOMS,     491},   L"491 Inside hut"                       },
        {{C_ROOMS,     492},   L"492 Mountain"                         },
        {{C_ROOMS,     493},   L"493 Dock with boat"                   },
        {{C_ROOMS,     494},   L"494 Dock with boat"                   },
        {{C_ROOMS,     495},   L"495 Dock with boat"                   },
        {{C_ROOMS,     496},   L"496 Dock"                             },
        {{C_ROOMS,     497},   L"497 Boat"                             },
        {{C_ROOMS,     498},   L"498 Tall waterfall, cutscene"         },
        {{C_ROOMS,     499},   L"499 Inside hut"                       },
        {{C_ROOMS,     500},   L"500 Road"                             },
        {{C_ROOMS,     501},   L"501 Road"                             },
        {{C_ROOMS,     502},   L"502 Road"                             },
        {{C_ROOMS,     503},   L"503 Road"                             },
        {{C_ROOMS,     504},   L"504 Road"                             },
        {{C_ROOMS,     505},   L"505 Road"                             },
        {{C_ROOMS,     506},   L"506 Road"                             },
        {{C_ROOMS,     507},   L"507 Road"                             },
        {{C_ROOMS,     508},   L"508 Road"                             },
        {{C_ROOMS,     509},   L"509 Road"                             },
        {{C_ROOMS,     510},   L"510 Tibor, outside"                   },
        {{C_ROOMS,     511},   L"511 Tibor, outside"                   },
        {{C_ROOMS,     512},   L"512 Tibor, outside"                   },
        {{C_ROOMS,     513},   L"513 Tibor, outside"                   },
        {{C_ROOMS,     514},   L"514 Road"                             },
        {{C_ROOMS,     515},   L"515 Road"                             },
        {{C_ROOMS,     516},   L"516 Underground passageway"           },
        {{C_ROOMS,     517},   L"517 Waterfall shop"                   },
        {{C_ROOMS,     519},   L"519 Road"                             },
        {{C_ROOMS,     520},   L"520 Road"                             },
        {{C_ROOMS,     521},   L"521 Road"                             },
        {{C_ROOMS,     522},   L"522 Verla mine, save"                 },
        {{C_ROOMS,     523},   L"523 Lake"                             },
        {{C_ROOMS,     524},   L"524 Lake, lava"                       },
        {{C_ROOMS,     525},   L"525 Lake"                             },
        {{C_ROOMS,     526},   L"526 Lake, ouside of shrine"           },
        {{C_ROOMS,     527},   L"527 Inside hut, empty"                },
        {{C_ROOMS,     528},   L"528 Road"                             },
        {{C_ROOMS,     529},   L"529 Road, pit"                        },
        {{C_ROOMS,     530},   L"530 Road"                             },
        {{C_ROOMS,     531},   L"531 Road"                             },
        {{C_ROOMS,     532},   L"532 Underground passageway"           },
        {{C_ROOMS,     533},   L"533 Tibor, outside"                   },
        {{C_ROOMS,     534},   L"534 Tibor, outside"                   },
        {{C_ROOMS,     535},   L"535 Tibor, outside"                   },
        {{C_ROOMS,     536},   L"536 Tibor, outside"                   },
        {{C_ROOMS,     537},   L"537 Tibor, outside"                   },
        {{C_ROOMS,     538},   L"538 Tibor, outside"                   },
        {{C_ROOMS,     539},   L"539 Tibor, outside"                   },
        {{C_ROOMS,     540},   L"540 Road"                             },
        {{C_ROOMS,     541},   L"541 Road"                             },
        {{C_ROOMS,     542},   L"542 Road"                             },
        {{C_ROOMS,     543},   L"543 Dock"                             },
        {{C_ROOMS,     544},   L"544 Dock"                             },
        {{C_ROOMS,     545},   L"545 Outside"                          },
        {{C_ROOMS,     546},   L"546 Mountain, underground"            },
        {{C_ROOMS,     547},   L"547 Mountain, underground"            },
        {{C_ROOMS,     548},   L"548 Mountain, underground"            },
        {{C_ROOMS,     549},   L"549 Mountain, underground"            },
        {{C_ROOMS,     550},   L"550 Mountain, underground"            },
        {{C_ROOMS,     551},   L"551 Mountain, underground"            },
        {{C_ROOMS,     552},   L"552 Mountain, underground"            },
        {{C_ROOMS,     553},   L"553 Mountain, underground"            },
        {{C_ROOMS,     554},   L"554 Mountain, underground"            },
        {{C_ROOMS,     555},   L"555 Mountain, underground"            },
        {{C_ROOMS,     556},   L"556 Green maze"                       },
        {{C_ROOMS,     557},   L"557 Green maze"                       },
        {{C_ROOMS,     558},   L"558 Green maze"                       },
        {{C_ROOMS,     559},   L"559 Green maze"                       },
        {{C_ROOMS,     560},   L"560 Green Maze"                       },
        {{C_ROOMS,     561},   L"561 Green Maze"                       },
        {{C_ROOMS,     562},   L"562 Green Maze"                       },
        {{C_ROOMS,     563},   L"563 Green Maze"                       },
        {{C_ROOMS,     564},   L"564 Green Maze"                       },
        {{C_ROOMS,     565},   L"565 Green Maze"                       },
        {{C_ROOMS,     566},   L"566 Green Maze"                       },
        {{C_ROOMS,     567},   L"567 Green Maze"                       },
        {{C_ROOMS,     568},   L"568 Green Maze"                       },
        {{C_ROOMS,     569},   L"569 Green Maze"                       },
        {{C_ROOMS,     570},   L"570 Green Maze"                       },
        {{C_ROOMS,     571},   L"571 Green maze"                       },
        {{C_ROOMS,     572},   L"572 Green maze"                       },
        {{C_ROOMS,     573},   L"573 Green maze"                       },
        {{C_ROOMS,     574},   L"574 Green maze"                       },
        {{C_ROOMS,     575},   L"575 Green maze"                       },
        {{C_ROOMS,     576},   L"576 Green maze"                       },
        {{C_ROOMS,     577},   L"577 Green maze"                       },
        {{C_ROOMS,     578},   L"578 Green maze"                       },
        {{C_ROOMS,     579},   L"579 Green maze"                       },
        {{C_ROOMS,     580},   L"580 Green maze"                       },
        {{C_ROOMS,     581},   L"581 Green maze"                       },
        {{C_ROOMS,     582},   L"582 Green maze"                       },
        {{C_ROOMS,     583},   L"583 Green maze"                       },
        {{C_ROOMS,     584},   L"584 Green maze"                       },
        {{C_ROOMS,     585},   L"585 Green maze"                       },
        {{C_ROOMS,     586},   L"586 Green maze"                       },
        {{C_ROOMS,     587},   L"587 Green maze"                       },
        {{C_ROOMS,     588},   L"588 Green maze"                       },
        {{C_ROOMS,     589},   L"589 Green maze"                       },
        {{C_ROOMS,     590},   L"590 Green maze"                       },
        {{C_ROOMS,     591},   L"591 Green maze"                       },
        {{C_ROOMS,     592},   L"592 Massan village, outside"          },
        {{C_ROOMS,     593},   L"593 Massan village, hut"              },
        {{C_ROOMS,     594},   L"594 Massan village, hut"              },
        {{C_ROOMS,     595},   L"595 Massan village, hut"              },
        {{C_ROOMS,     596},   L"596 Massan village, shop"             },
        {{C_ROOMS,     597},   L"597 Massan village, church"           },
        {{C_ROOMS,     598},   L"598 Massan village, inn"              },
        {{C_ROOMS,     599},   L"599 Massan village, hut"              },
        {{C_ROOMS,     600},   L"600 Massan village, inn, second floor"},
        {{C_ROOMS,     601},   L"601 Gumi village, stake"              },
        {{C_ROOMS,     602},   L"602 Gumi village"                     },
        {{C_ROOMS,     603},   L"603 Gumi village"                     },
        {{C_ROOMS,     604},   L"604 Gumi village, hut"                },
        {{C_ROOMS,     605},   L"605 Gumi village, hut"                },
        {{C_ROOMS,     606},   L"606 Gumi village, hut"                },
        {{C_ROOMS,     607},   L"607 Gumi village, church"             },
        {{C_ROOMS,     608},   L"608 Gumi village, inn first floor"    },
        {{C_ROOMS,     609},   L"609 Gumi village, inn secoond floor"  },
        {{C_ROOMS,     610},   L"610 Ryuma"                            },
        {{C_ROOMS,     611},   L"611 Ryuma"                            },
        {{C_ROOMS,     612},   L"612 Ryuma, lighthouse"                },
        {{C_ROOMS,     613},   L"613 Ryuma"                            },
        {{C_ROOMS,     614},   L"614 Ryuma, church"                    },
        {{C_ROOMS,     615},   L"615 Ryuma, shop"                      },
        {{C_ROOMS,     616},   L"616 Ryuma"                            },
        {{C_ROOMS,     617},   L"617 Ryuma"                            },
        {{C_ROOMS,     618},   L"618 Ryuma"                            },
        {{C_ROOMS,     619},   L"619 Ryuma"                            },
        {{C_ROOMS,     620},   L"620 Ryuma"                            },
        {{C_ROOMS,     621},   L"621 Ryuma"                            },
        {{C_ROOMS,     622},   L"622 Ryuma"                            },
        {{C_ROOMS,     623},   L"623 Ryuma, inn"                       },
        {{C_ROOMS,     624},   L"624 Ryuma, inn"                       },
        {{C_ROOMS,     625},   L"625 Ryuma, lighthouse stairs"         },
        {{C_ROOMS,     626},   L"626 Ryuma, lighthouse stairs"         },
        {{C_ROOMS,     627},   L"627 Ryuma, lighthouse top"            },
        {{C_ROOMS,     628},   L"628 Ryuma, lighthouse top (night)"    },
        {{C_ROOMS,     629},   L"629 Ryuma, lighthouse top"            },
        {{C_ROOMS,     630},   L"630 Mercator"                         },
        {{C_ROOMS,     631},   L"631 Mercator"                         },
        {{C_ROOMS,     632},   L"632 Mercator"                         },
        {{C_ROOMS,     633},   L"633 Mercator"                         },
        {{C_ROOMS,     634},   L"634 Mercator"                         },
        {{C_ROOMS,     635},   L"635 Mercator"                         },
        {{C_ROOMS,     636},   L"636 Mercator"                         },
        {{C_ROOMS,     637},   L"637 Mercator"                         },
        {{C_ROOMS,     638},   L"638 Mercator"                         },
        {{C_ROOMS,     639},   L"639 Mercator"                         },
        {{C_ROOMS,     640},   L"640 Mercator"                         },
        {{C_ROOMS,     641},   L"641 Mercator harbor"                  },
        {{C_ROOMS,     642},   L"642 Mercator harbor"                  },
        {{C_ROOMS,     643},   L"643 Mercator harbor"                  },
        {{C_ROOMS,     644},   L"644 Mercator harbor"                  },
        {{C_ROOMS,     645},   L"645 Underground passage"              },
        {{C_ROOMS,     646},   L"646 Crypt"                            },
        {{C_ROOMS,     647},   L"647 Crypt"                            },
        {{C_ROOMS,     648},   L"648 Crypt"                            },
        {{C_ROOMS,     649},   L"649 Crypt"                            },
        {{C_ROOMS,     650},   L"650 Crypt"                            },
        {{C_ROOMS,     651},   L"651 Crypt, mummy's room"              },
        {{C_ROOMS,     652},   L"652 Crypt"                            },
        {{C_ROOMS,     653},   L"653 Crypt"                            },
        {{C_ROOMS,     654},   L"654 Crypt"                            },
        {{C_ROOMS,     655},   L"655 Crypt"                            },
        {{C_ROOMS,     656},   L"656 Crypt"                            },
        {{C_ROOMS,     657},   L"657 Crypt"                            },
        {{C_ROOMS,     658},   L"658 Crypt"                            },
        {{C_ROOMS,     659},   L"659 Crypt"                            },
        {{C_ROOMS,     660},   L"660 Mercator"                         },
        {{C_ROOMS,     661},   L"661 Mercator"                         },
        {{C_ROOMS,     662},   L"662 Mercator"                         },
        {{C_ROOMS,     663},   L"663 Casino, corridor"                 },
        {{C_ROOMS,     664},   L"664 Casino, roulette"                 },
        {{C_ROOMS,     665},   L"665 Casino, sprint race"              },
        {{C_ROOMS,     666},   L"666 Casino, chicken"                  },
        {{C_ROOMS,     667},   L"667 Mercator"                         },
        {{C_ROOMS,     668},   L"668 Mercator"                         },
        {{C_ROOMS,     669},   L"669 Mercator"                         },
        {{C_ROOMS,     670},   L"670 Mercator"                         },
        {{C_ROOMS,     671},   L"671 Mercator"                         },
        {{C_ROOMS,     672},   L"672 Mercator, throw game"             },
        {{C_ROOMS,     673},   L"673 Mercator"                         },
        {{C_ROOMS,     674},   L"674 Mercator"                         },
        {{C_ROOMS,     675},   L"675 Mercator"                         },
        {{C_ROOMS,     676},   L"676 Mercator"                         },
        {{C_ROOMS,     677},   L"677 Mercator"                         },
        {{C_ROOMS,     678},   L"678 Mercator"                         },
        {{C_ROOMS,     679},   L"679 Mercator"                         },
        {{C_ROOMS,     680},   L"680 Madam yard's"                     },
        {{C_ROOMS,     681},   L"681 Mercator prison"                  },
        {{C_ROOMS,     682},   L"682 Mercator prison"                  },
        {{C_ROOMS,     683},   L"683 Mercator"                         },
        {{C_ROOMS,     684},   L"684 Mercator"                         },
        {{C_ROOMS,     685},   L"685 Mercator"                         },
        {{C_ROOMS,     686},   L"686 Mercator"                         },
        {{C_ROOMS,     687},   L"687 Mercator"                         },
        {{C_ROOMS,     688},   L"688 Mercator"                         },
        {{C_ROOMS,     689},   L"689 Mercator"                         },
        {{C_ROOMS,     690},   L"690 Mercator"                         },
        {{C_ROOMS,     691},   L"691 Mercator"                         },
        {{C_ROOMS,     692},   L"692 Mercator"                         },
        {{C_ROOMS,     693},   L"693 Mercator"                         },
        {{C_ROOMS,     694},   L"694 Mercator old woman house. First floor"},
        {{C_ROOMS,     695},   L"695 Mercator, empty shop"             },
        {{C_ROOMS,     696},   L"696 Mercator, drug store"             },
        {{C_ROOMS,     697},   L"697 Mercator, variety shop"           },
        {{C_ROOMS,     698},   L"698 Mercator, shop's backroom"        },
        {{C_ROOMS,     699},   L"699 Mercator, church"                 },
        {{C_ROOMS,     700},   L"700 Mercator, church"                 },
        {{C_ROOMS,     701},   L"701 Mercator"                         },
        {{C_ROOMS,     702},   L"702 Mercator"                         },
        {{C_ROOMS,     703},   L"703 Mercator"                         },
        {{C_ROOMS,     704},   L"704 Mercator"                         },
        {{C_ROOMS,     705},   L"705 Mercator"                         },
        {{C_ROOMS,     706},   L"706 Mercator"                         },
        {{C_ROOMS,     707},   L"707 Madame yard's, corridor"          },
        {{C_ROOMS,     708},   L"708 Madame yard's"                    },
        {{C_ROOMS,     709},   L"709 Mercator, old woman's house first floor"},
        {{C_ROOMS,     710},   L"710 Madame yard's"                    },
        {{C_ROOMS,     711},   L"711 Verla, trap"                      },
        {{C_ROOMS,     712},   L"712 Verla"                            },
        {{C_ROOMS,     713},   L"713 Verla"                            },
        {{C_ROOMS,     714},   L"714 Verla"                            },
        {{C_ROOMS,     715},   L"715 Verla"                            },
        {{C_ROOMS,     716},   L"716 Verla"                            },
        {{C_ROOMS,     717},   L"717 Verla"                            },
        {{C_ROOMS,     718},   L"718 Verla"                            },
        {{C_ROOMS,     719},   L"719 Verla"                            },
        {{C_ROOMS,     720},   L"720 Verla"                            },
        {{C_ROOMS,     721},   L"721 Verla, church"                    },
        {{C_ROOMS,     722},   L"722 Verla"                            },
        {{C_ROOMS,     723},   L"723 Verla"                            },
        {{C_ROOMS,     724},   L"724 Verla"                            },
        {{C_ROOMS,     725},   L"725 Verla"                            },
        {{C_ROOMS,     726},   L"726 Destel"                           },
        {{C_ROOMS,     727},   L"727 Destel"                           },
        {{C_ROOMS,     728},   L"728 Destel"                           },
        {{C_ROOMS,     729},   L"729 Destel, inn first floor"          },
        {{C_ROOMS,     730},   L"730 Destel, inn second floor"         },
        {{C_ROOMS,     731},   L"731 Destel"                           },
        {{C_ROOMS,     732},   L"732 Destel"                           },
        {{C_ROOMS,     733},   L"733 Destel"                           },
        {{C_ROOMS,     734},   L"734 Destel"                           },
        {{C_ROOMS,     735},   L"735 Destel"                           },
        {{C_ROOMS,     736},   L"736 Destel, church"                   },
        {{C_ROOMS,     737},   L"737 Kazalt village"                   },
        {{C_ROOMS,     738},   L"738 Kazalt"                           },
        {{C_ROOMS,     739},   L"739 Kazalt"                           },
        {{C_ROOMS,     740},   L"740 Kazalt"                           },
        {{C_ROOMS,     741},   L"741 Kazalt"                           },
        {{C_ROOMS,     742},   L"742 Kazalt"                           },
        {{C_ROOMS,     743},   L"743 Kazalt"                           },
        {{C_ROOMS,     744},   L"744 Kazalt"                           },
        {{C_ROOMS,     745},   L"745 Kazalt, inn"                      },
        {{C_ROOMS,     746},   L"746 Kazalt, inn"                      },
        {{C_ROOMS,     747},   L"747 Kazalt, shop"                     },
        {{C_ROOMS,     748},   L"748 Kazalt"                           },
        {{C_ROOMS,     749},   L"749 Kazalt, church"                   },
        {{C_ROOMS,     750},   L"750 Mir's tower"                      },
        {{C_ROOMS,     751},   L"751 Mir's tower"                      },
        {{C_ROOMS,     752},   L"752 Mir's tower"                      },
        {{C_ROOMS,     753},   L"753 Mir's tower"                      },
        {{C_ROOMS,     754},   L"754 Mir's tower"                      },
        {{C_ROOMS,     755},   L"755 Mir's tower"                      },
        {{C_ROOMS,     756},   L"756 Mir's tower"                      },
        {{C_ROOMS,     757},   L"757 Mir's tower"                      },
        {{C_ROOMS,     758},   L"758 Mir's tower"                      },
        {{C_ROOMS,     759},   L"759 Mir's tower"                      },
        {{C_ROOMS,     760},   L"760 Mir's tower"                      },
        {{C_ROOMS,     761},   L"761 Mir's tower"                      },
        {{C_ROOMS,     762},   L"762 Mir's tower"                      },
        {{C_ROOMS,     763},   L"763 Mir's tower"                      },
        {{C_ROOMS,     764},   L"764 Mir's tower"                      },
        {{C_ROOMS,     765},   L"765 Mir's tower"                      },
        {{C_ROOMS,     766},   L"766 Mir's tower"                      },
        {{C_ROOMS,     767},   L"767 Mir's tower"                      },
        {{C_ROOMS,     768},   L"768 Mir's tower"                      },
        {{C_ROOMS,     769},   L"769 Mir's tower"                      },
        {{C_ROOMS,     770},   L"770 Mir's tower"                      },
        {{C_ROOMS,     771},   L"771 Mir's tower"                      },
        {{C_ROOMS,     772},   L"772 Mir's tower"                      },
        {{C_ROOMS,     773},   L"773 Mir's tower"                      },
        {{C_ROOMS,     774},   L"774 Mir's tower"                      },
        {{C_ROOMS,     775},   L"775 Mir's tower"                      },
        {{C_ROOMS,     776},   L"776 Mir's tower"                      },
        {{C_ROOMS,     777},   L"777 Mir's tower"                      },
        {{C_ROOMS,     778},   L"778 Mir's tower"                      },
        {{C_ROOMS,     779},   L"779 Mir's tower"                      },
        {{C_ROOMS,     780},   L"780 Mir's tower"                      },
        {{C_ROOMS,     781},   L"781 Mir's tower"                      },
        {{C_ROOMS,     782},   L"782 Mir's tower"                      },
        {{C_ROOMS,     783},   L"783 Mir's tower"                      },
        {{C_ROOMS,     784},   L"784 Mir's tower, Mir's lair"          },
        {{C_ROOMS,     785},   L"785 Helga's hut"                      },
        {{C_ROOMS,     786},   L"786 Helga's hut"                      },
        {{C_ROOMS,     787},   L"787 Helga's hut"                      },
        {{C_ROOMS,     788},   L"788 Helga's hut"                      },
        {{C_ROOMS,     789},   L"789 Helga's hut"                      },
        {{C_ROOMS,     790},   L"790 Helga's hut"                      },
        {{C_ROOMS,     791},   L"791 Helga's hut"                      },
        {{C_ROOMS,     792},   L"792 Helga's hut"                      },
        {{C_ROOMS,     793},   L"793 Helga's hut"                      },
        {{C_ROOMS,     794},   L"794 Helga's hut"                      },
        {{C_ROOMS,     795},   L"795 Helga's hut"                      },
        {{C_ROOMS,     796},   L"796 Helga's hut"                      },
        {{C_ROOMS,     797},   L"797 Helga's hut"                      },
        {{C_ROOMS,     798},   L"798 Helga's hut"                      },
        {{C_ROOMS,     799},   L"799 Helga's hut"                      },
        {{C_ROOMS,     800},   L"800 Helga's hut"                      },
        {{C_ROOMS,     801},   L"801 Helga's hut"                      },
        {{C_ROOMS,     802},   L"802 Helga's hut"                      },
        {{C_ROOMS,     803},   L"803 Massan cave"                      },
        {{C_ROOMS,     804},   L"804 Massan cave"                      },
        {{C_ROOMS,     805},   L"805 Massan cave"                      },
        {{C_ROOMS,     806},   L"806 Massan cave"                      },
        {{C_ROOMS,     807},   L"807 Massan cave"                      },
        {{C_ROOMS,     808},   L"808 Tibor"                            },
        {{C_ROOMS,     809},   L"809 Tibor"                            },
        {{C_ROOMS,     810},   L"810 Tibor"                            },
        {{C_ROOMS,     811},   L"811 Tibor"                            },
        {{C_ROOMS,     812},   L"812 Tibor"                            },
        {{C_ROOMS,     813},   L"813 Tibor"                            },
        {{C_ROOMS,     814},   L"814 Tibor"                            },
        {{C_ROOMS,     815},   L"815 Tibor"                            },
        {{C_BGMS,      0},     L"[00] The Marquis' Invitation"         },
        {{C_BGMS,      1},     L"[01] Premonition of Trouble"          },
        {{C_BGMS,      2},     L"[02] Overworld"                       },
        {{C_BGMS,      3},     L"[03] Bustling Street"                 },
        {{C_BGMS,      4},     L"[04] Torchlight"                      },
        {{C_BGMS,      5},     L"[05] Prayers to God"                  },
        {{C_BGMS,      6},     L"[06] Gumi"                            },
        {{C_BGMS,      7},     L"[07] Beneath the Mysterious Tree"     },
        {{C_BGMS,      8},     L"[08] Overworld"                       },
        {{C_BGMS,      9},     L"[09] The King's Chamber"              },
        {{C_BGMS,      10},    L"[0A] Mysterious Island"               },
        {{C_BGMS,      11},    L"[0B] The Death God's Invitation"      },
        {{C_BGMS,      12},    L"[0C] Deserted Street Corner"          },
        {{C_BGMS,      13},    L"[0D] Labrynth"                        },
        {{C_BGMS,      14},    L"[0E] The Silence, the Darkness, and..."},
        {{C_BGMS,      15},    L"[0F] Light of the Setting Sun"        },
        {{C_BGMS,      16},    L"[10] Friday and a Soft Breeze"        },
        {{C_BGMS,      17},    L"[11] Divine Guardian of the Maze"     },
        {{C_BGMS,      18},    L"[12] Fade Out"                        },
        {{C_SOUNDS,    0},     L"<00> <Null>"                          },
        {{C_SOUNDS,    1},     L"<01> Bustling Street"                 },
        {{C_SOUNDS,    2},     L"<02> Torchlight"                      },
        {{C_SOUNDS,    3},     L"<03> Premonition of Trouble"          },
        {{C_SOUNDS,    4},     L"<04> Fanfare 1"                       },
        {{C_SOUNDS,    5},     L"<05> Receive Item"                    },
        {{C_SOUNDS,    6},     L"<06> Rest"                            },
        {{C_SOUNDS,    7},     L"<07> Save Game"                       },
        {{C_SOUNDS,    8},     L"<08> Status Heal"                     },
        {{C_SOUNDS,    9},     L"<09> Poisoned"                        },
        {{C_SOUNDS,    10},    L"<0A> The Death God's Invitation"      },
        {{C_SOUNDS,    11},    L"<0B> Duke's Fanfare"                  },
        {{C_SOUNDS,    12},    L"<0C> Fanfare 2"                       },
        {{C_SOUNDS,    13},    L"<0D> Einstein Whistle"                },
        {{C_SOUNDS,    14},    L"<0E> Black Market"                    },
        {{C_SOUNDS,    15},    L"<0F> Surprise"                        },
        {{C_SOUNDS,    16},    L"<10> Title"                           },
        {{C_SOUNDS,    17},    L"<11> Let's Go On An Adventure"        },
        {{C_SOUNDS,    18},    L"<12> Treasure Hunter Lyle"            },
        {{C_SOUNDS,    19},    L"<13> Seeking Treasure"                },
        {{C_SOUNDS,    20},    L"<14> Deserted Street Corner"          },
        {{C_SOUNDS,    21},    L"<15> Friday and a Soft Breeze"        },
        {{C_SOUNDS,    22},    L"<16> Hey, It's Your Turn!"            },
        {{C_SOUNDS,    27},    L"<1B> To The Great Adventurers"        },
        {{C_SOUNDS,    29},    L"<1D> Beneath the Mysterious Tree"     },
        {{C_SOUNDS,    31},    L"<1F> Urgent, Nigel!"                  },
        {{C_SOUNDS,    33},    L"<21> Prayers To God"                  },
        {{C_SOUNDS,    34},    L"<22> Light Of The Setting Sun"        },
        {{C_SOUNDS,    35},    L"<23> Wicked God's Banquet"            },
        {{C_SOUNDS,    36},    L"<24> Heh Heh, I Think I Will Disrupt This Good Cheer"},
        {{C_SOUNDS,    37},    L"<25> The Marquis' Invitation"         },
        {{C_SOUNDS,    38},    L"<26> The King's Chamber"              },
        {{C_SOUNDS,    39},    L"<27> Mysterious Island"               },
        {{C_SOUNDS,    40},    L"<28> Friday's Memory"                 },
        {{C_SOUNDS,    41},    L"<29> Divine Guardian of the Maze"     },
        {{C_SOUNDS,    42},    L"<2A> The Silence, the Darkness, and..."},
        {{C_SOUNDS,    43},    L"<2B> Labrynth"                        },
        {{C_SOUNDS,    44},    L"<2C> A Ballad For Princess Loria"     },
        {{C_SOUNDS,    45},    L"<2D> A Ballad For Princess Loria (Loop)"},
        {{C_SOUNDS,    46},    L"<2E> Pink Book"                       },
        {{C_SOUNDS,    47},    L"<2F> Adventure Spirit"                },
        {{C_SOUNDS,    65},    L"<41> Skeleton Talk"                   },
        {{C_SOUNDS,    66},    L"<42> Cursor Move"                     },
        {{C_SOUNDS,    67},    L"<43> Cursor Select"                   },
        {{C_SOUNDS,    68},    L"<44> Error Buzz"                      },
        {{C_SOUNDS,    69},    L"<45> Speaker Pitch 8"                 },
        {{C_SOUNDS,    70},    L"<46> Speaker Pitch 7"                 },
        {{C_SOUNDS,    71},    L"<47> Speaker Pitch 6"                 },
        {{C_SOUNDS,    72},    L"<48> Speaker Pitch 5"                 },
        {{C_SOUNDS,    73},    L"<49> Speaker Pitch 4"                 },
        {{C_SOUNDS,    74},    L"<4A> Speaker Pitch 3"                 },
        {{C_SOUNDS,    75},    L"<4B> Speaker Pitch 2"                 },
        {{C_SOUNDS,    76},    L"<4C> Speaker Pitch 1"                 },
        {{C_SOUNDS,    77},    L"<4D> Warp"                            },
        {{C_SOUNDS,    78},    L"<4E> Drum"                            },
        {{C_SOUNDS,    79},    L"<4F> Cymbal"                          },
        {{C_SOUNDS,    80},    L"<50> Snare Drum"                      },
        {{C_SOUNDS,    81},    L"<51> Sword Swing"                     },
        {{C_SOUNDS,    82},    L"<52> Sword Hitting Stone"             },
        {{C_SOUNDS,    83},    L"<53> Jump"                            },
        {{C_SOUNDS,    84},    L"<54> Fall"                            },
        {{C_SOUNDS,    85},    L"<55> Exit"                            },
        {{C_SOUNDS,    86},    L"<56> Throw"                           },
        {{C_SOUNDS,    87},    L"<57> Enemy Cry"                       },
        {{C_SOUNDS,    88},    L"<58> Door Lock"                       },
        {{C_SOUNDS,    89},    L"<59> Rumble"                          },
        {{C_SOUNDS,    90},    L"<5A> Health Recover"                  },
        {{C_SOUNDS,    91},    L"<5B> Dog Transform"                   },
        {{C_SOUNDS,    92},    L"<5C> HP Absorb"                       },
        {{C_SOUNDS,    93},    L"<5D> Land"                            },
        {{C_SOUNDS,    94},    L"<5E> Climb"                           },
        {{C_SOUNDS,    95},    L"<5F> Throw Alt"                       },
        {{C_SOUNDS,    96},    L"<60> Bounce"                          },
        {{C_SOUNDS,    97},    L"<61> Player Take Damage"              },
        {{C_SOUNDS,    98},    L"<62> Player Drop Object Alt"          },
        {{C_SOUNDS,    99},    L"<63> Player Drop Object"              },
        {{C_SOUNDS,    100},   L"<64> Player Take Damage Alt"          },
        {{C_SOUNDS,    101},   L"<65> Player Die"                      },
        {{C_SOUNDS,    102},   L"<66> Enemy Die"                       },
        {{C_SOUNDS,    103},   L"<67> Enemy Take Damage"               },
        {{C_SOUNDS,    104},   L"<68> Open Menu"                       },
        {{C_SOUNDS,    105},   L"<69> Pick Up Item"                    },
        {{C_SOUNDS,    106},   L"<6A> Pick Up Gold"                    },
        {{C_SOUNDS,    107},   L"<6B> Kazalt Warp"                     },
        {{C_SOUNDS,    108},   L"<6C> Switch"                          },
        {{C_SOUNDS,    109},   L"<6D> Explosion"                       },
        {{C_SOUNDS,    110},   L"<6E> Thud"                            },
        {{C_SOUNDS,    111},   L"<6F> Enemy Die Alt"                   },
        {{C_SOUNDS,    112},   L"<70> Enemy Take Damage Alt"           },
        {{C_SOUNDS,    113},   L"<71> Fireball 1"                      },
        {{C_SOUNDS,    114},   L"<72> Fireball 2"                      },
        {{C_SOUNDS,    115},   L"<73> Short Rumble"                    },
        {{C_SOUNDS,    116},   L"<74> Permanent Switch"                },
        {{C_SOUNDS,    117},   L"<75> Latch"                           },
        {{C_SOUNDS,    118},   L"<76> Friday Magic"                    },
        {{C_SOUNDS,    119},   L"<77> Slash 1"                         },
        {{C_SOUNDS,    120},   L"<78> Slash 2"                         },
        {{C_SOUNDS,    121},   L"<79> Mir Warp"                        },
        {{C_SOUNDS,    122},   L"<7A> Poison"                          },
        {{C_SOUNDS,    253},   L"<FD> Fade Out"                        },
        {{C_SOUNDS,    254},   L"<FE> Stop"                            },
        {{C_SOUNDS,    255},   L"<FF> Load From D0"                    },
        {{C_ENTITIES,  0},     L"Nigel"                                },
        {{C_ENTITIES,  1},     L"Old Man"                              },
        {{C_ENTITIES,  2},     L"Male Red Bear"                        },
        {{C_ENTITIES,  3},     L"Boy"                                  },
        {{C_ENTITIES,  4},     L"Orc 1"                                },
        {{C_ENTITIES,  5},     L"Orc 2"                                },
        {{C_ENTITIES,  6},     L"Orc 3"                                },
        {{C_ENTITIES,  7},     L"Worm 1"                               },
        {{C_ENTITIES,  8},     L"Worm 2"                               },
        {{C_ENTITIES,  9},     L"Worm 3"                               },
        {{C_ENTITIES,  10},    L"Moneybag"                             },
        {{C_ENTITIES,  11},    L"Man 1"                                },
        {{C_ENTITIES,  12},    L"Woman 1"                              },
        {{C_ENTITIES,  13},    L"Girl"                                 },
        {{C_ENTITIES,  14},    L"Dog"                                  },
        {{C_ENTITIES,  15},    L"Chicken"                              },
        {{C_ENTITIES,  16},    L"Priest"                               },
        {{C_ENTITIES,  17},    L"Vase"                                 },
        {{C_ENTITIES,  18},    L"Chest"                                },
        {{C_ENTITIES,  19},    L"Small Grey Ball"                      },
        {{C_ENTITIES,  20},    L"Large Grey Ball"                      },
        {{C_ENTITIES,  21},    L"Small Yellow Platform"                },
        {{C_ENTITIES,  22},    L"Crate"                                },
        {{C_ENTITIES,  23},    L"Ninja 1"                              },
        {{C_ENTITIES,  24},    L"Ninja 2"                              },
        {{C_ENTITIES,  25},    L"Ninja 3"                              },
        {{C_ENTITIES,  26},    L"Lizard 1"                             },
        {{C_ENTITIES,  27},    L"Lizard 2"                             },
        {{C_ENTITIES,  28},    L"Lizard 3"                             },
        {{C_ENTITIES,  29},    L"Knight 1"                             },
        {{C_ENTITIES,  30},    L"Knight 2"                             },
        {{C_ENTITIES,  31},    L"Knight 3"                             },
        {{C_ENTITIES,  32},    L"Ghost 1"                              },
        {{C_ENTITIES,  33},    L"Ghost 2"                              },
        {{C_ENTITIES,  34},    L"Ghost 3"                              },
        {{C_ENTITIES,  35},    L"Mummy 1"                              },
        {{C_ENTITIES,  36},    L"Mummy 2"                              },
        {{C_ENTITIES,  37},    L"Mummy 3"                              },
        {{C_ENTITIES,  38},    L"Unicorn 1"                            },
        {{C_ENTITIES,  39},    L"Unicorn 2"                            },
        {{C_ENTITIES,  40},    L"Unicorn 3"                            },
        {{C_ENTITIES,  41},    L"Skeleton 1"                           },
        {{C_ENTITIES,  42},    L"Skeleton 2"                           },
        {{C_ENTITIES,  43},    L"Skeleton 3"                           },
        {{C_ENTITIES,  44},    L"Mimic 1"                              },
        {{C_ENTITIES,  45},    L"Mimic 2"                              },
        {{C_ENTITIES,  46},    L"Mimic 3"                              },
        {{C_ENTITIES,  47},    L"Child Red Bear"                       },
        {{C_ENTITIES,  48},    L"Male Dwarf"                           },
        {{C_ENTITIES,  49},    L"Female Yellow Bear"                   },
        {{C_ENTITIES,  50},    L"Soldier"                              },
        {{C_ENTITIES,  51},    L"Madame Yard"                          },
        {{C_ENTITIES,  52},    L"Dexter"                               },
        {{C_ENTITIES,  53},    L"Raft"                                 },
        {{C_ENTITIES,  54},    L"Mushroom 1"                           },
        {{C_ENTITIES,  55},    L"Mushroom 2"                           },
        {{C_ENTITIES,  56},    L"Mushroom 3"                           },
        {{C_ENTITIES,  57},    L"Giant 1"                              },
        {{C_ENTITIES,  58},    L"Giant 2"                              },
        {{C_ENTITIES,  59},    L"Giant 3"                              },
        {{C_ENTITIES,  60},    L"Bubble 1"                             },
        {{C_ENTITIES,  61},    L"Bubble 2"                             },
        {{C_ENTITIES,  62},    L"Bubble 3"                             },
        {{C_ENTITIES,  63},    L"Old Lady"                             },
        {{C_ENTITIES,  64},    L"Male Yellow Bear"                     },
        {{C_ENTITIES,  65},    L"Child Yellow Bear"                    },
        {{C_ENTITIES,  66},    L"Fara stake"                           },
        {{C_ENTITIES,  67},    L"Praying Yellow Bear"                  },
        {{C_ENTITIES,  68},    L"Skeleton Statue 1"                    },
        {{C_ENTITIES,  69},    L"Praying Red Bear"                     },
        {{C_ENTITIES,  70},    L"Skeleton Statue 2"                    },
        {{C_ENTITIES,  71},    L"Female Red Bear"                      },
        {{C_ENTITIES,  72},    L"Female Dwarf"                         },
        {{C_ENTITIES,  73},    L"Small Grey Spiked Ball"               },
        {{C_ENTITIES,  74},    L"Large Grey Spiked Ball"               },
        {{C_ENTITIES,  75},    L"Sacred Tree"                          },
        {{C_ENTITIES,  76},    L"Large Wood Platform"                  },
        {{C_ENTITIES,  77},    L"Injured Dog"                          },
        {{C_ENTITIES,  78},    L"Dead Body"                            },
        {{C_ENTITIES,  79},    L"Woman 2"                              },
        {{C_ENTITIES,  80},    L"Man 2"                                },
        {{C_ENTITIES,  81},    L"Invisible Cube"                       },
        {{C_ENTITIES,  82},    L"Ink"                                  },
        {{C_ENTITIES,  83},    L"Large Concrete Block"                 },
        {{C_ENTITIES,  84},    L"Square Switch"                        },
        {{C_ENTITIES,  85},    L"Round Switch"                         },
        {{C_ENTITIES,  86},    L"Unused Small Yellow Platform"         },
        {{C_ENTITIES,  87},    L"Unused Small Grey Platform"           },
        {{C_ENTITIES,  88},    L"Unused Small Green Platform"          },
        {{C_ENTITIES,  89},    L"Small Thin Yellow Platform"           },
        {{C_ENTITIES,  90},    L"Small Thin Grey Platform"             },
        {{C_ENTITIES,  91},    L"Unused Small Thin Green Platform"     },
        {{C_ENTITIES,  92},    L"Unused Large Dark Platform"           },
        {{C_ENTITIES,  93},    L"Large Thin Grey Platform"             },
        {{C_ENTITIES,  94},    L"Unused Large Thin Green Platform"     },
        {{C_ENTITIES,  95},    L"Unused Large Thin Yellow Platform"    },
        {{C_ENTITIES,  96},    L"Item Box"                             },
        {{C_ENTITIES,  97},    L"Friday"                               },
        {{C_ENTITIES,  98},    L"Large Boulder"                        },
        {{C_ENTITIES,  99},    L"Nigel in Bed"                         },
        {{C_ENTITIES,  100},   L"Godess Statue"                        },
        {{C_ENTITIES,  101},   L"2-Way Signpost"                       },
        {{C_ENTITIES,  102},   L"3-Way Signpost"                       },
        {{C_ENTITIES,  103},   L"Gate S"                               },
        {{C_ENTITIES,  104},   L"Gate N"                               },
        {{C_ENTITIES,  105},   L"Kayla"                                },
        {{C_ENTITIES,  106},   L"Wally"                                },
        {{C_ENTITIES,  107},   L"Woman 3"                              },
        {{C_ENTITIES,  108},   L"Locked Door"                          },
        {{C_ENTITIES,  109},   L"Man in bed"                           },
        {{C_ENTITIES,  110},   L"Lord Arthur"                          },
        {{C_ENTITIES,  111},   L"Kayla in Bath"                        },
        {{C_ENTITIES,  112},   L"Duke"                                 },
        {{C_ENTITIES,  113},   L"Small Wood Platform"                  },
        {{C_ENTITIES,  114},   L"Small Thin Dark Grey Platform"        },
        {{C_ENTITIES,  115},   L"Yellow Old Man"                       },
        {{C_ENTITIES,  116},   L"Man with Blue Shirt"                  },
        {{C_ENTITIES,  117},   L"Chef"                                 },
        {{C_ENTITIES,  118},   L"Princess"                             },
        {{C_ENTITIES,  119},   L"Golem Statue 1"                       },
        {{C_ENTITIES,  120},   L"Mir Magic Barrier"                    },
        {{C_ENTITIES,  121},   L"Sailor"                               },
        {{C_ENTITIES,  122},   L"Pockets"                              },
        {{C_ENTITIES,  123},   L"Skeleton Priest"                      },
        {{C_ENTITIES,  124},   L"Mir"                                  },
        {{C_ENTITIES,  125},   L"Unused Bird 1"                        },
        {{C_ENTITIES,  126},   L"Unused Bird 2"                        },
        {{C_ENTITIES,  127},   L"Unused Bird 3"                        },
        {{C_ENTITIES,  128},   L"Moralis"                              },
        {{C_ENTITIES,  129},   L"Bubble 4"                             },
        {{C_ENTITIES,  130},   L"Bubble 5"                             },
        {{C_ENTITIES,  131},   L"Bubble 6"                             },
        {{C_ENTITIES,  132},   L"Gnome"                                },
        {{C_ENTITIES,  133},   L"Zak"                                  },
        {{C_ENTITIES,  134},   L"Mir Wall Barrier"                     },
        {{C_ENTITIES,  135},   L"Small Fireball"                       },
        {{C_ENTITIES,  136},   L"Reaper 1"                             },
        {{C_ENTITIES,  137},   L"Reaper 2"                             },
        {{C_ENTITIES,  138},   L"Unused Reaper 3"                      },
        {{C_ENTITIES,  139},   L"Golem Statue 2"                       },
        {{C_ENTITIES,  140},   L"Corrupted Round Switch"               },
        {{C_ENTITIES,  141},   L"Small Green Spiked Ball"              },
        {{C_ENTITIES,  142},   L"Large Grey Spiked Ball"               },
        {{C_ENTITIES,  143},   L"Ghost Generator 1"                    },
        {{C_ENTITIES,  144},   L"Ghost Generator 2"                    },
        {{C_ENTITIES,  145},   L"Ghost Generator 3"                    },
        {{C_ENTITIES,  146},   L"Golem 1"                              },
        {{C_ENTITIES,  147},   L"Golem 2"                              },
        {{C_ENTITIES,  148},   L"Golem 3"                              },
        {{C_ENTITIES,  149},   L"Spectre 1"                            },
        {{C_ENTITIES,  150},   L"Spectre 2"                            },
        {{C_ENTITIES,  151},   L"Spectre 3"                            },
        {{C_ENTITIES,  152},   L"Unused Small Blue Ball"               },
        {{C_ENTITIES,  153},   L"Small Red Ball"                       },
        {{C_ENTITIES,  154},   L"Unused Large Blue Ball"               },
        {{C_ENTITIES,  155},   L"Large Red Ball"                       },
        {{C_ENTITIES,  156},   L"Unused Magic Fox"                     },
        {{C_ENTITIES,  157},   L"Spinner 1"                            },
        {{C_ENTITIES,  158},   L"Duke Chair"                           },
        {{C_ENTITIES,  159},   L"Miro"                                 },
        {{C_ENTITIES,  160},   L"Ifrit"                                },
        {{C_ENTITIES,  161},   L"Ifrit Fireball"                       },
        {{C_ENTITIES,  162},   L"Gola"                                 },
        {{C_ENTITIES,  163},   L"Pink Golem Statue"                    },
        {{C_ENTITIES,  164},   L"Gold Golem Statue"                    },
        {{C_ENTITIES,  165},   L"Nole"                                 },
        {{C_ENTITIES,  166},   L"Nole Axe Projectile"                  },
        {{C_ENTITIES,  167},   L"Stone Warrior 1"                      },
        {{C_ENTITIES,  168},   L"Zak Boomerang"                        },
        {{C_ENTITIES,  169},   L"1-Way Signpost"                       },
        {{C_ENTITIES,  170},   L"Spinner 2"                            },
        {{C_ENTITIES,  171},   L"Stone Warrior 2"                      },
        {{C_ENTITIES,  172},   L"Gola Fireball"                        },
        {{C_ENTITIES,  173},   L"?AD"                                  },
        {{C_ENTITIES,  174},   L"?AE"                                  },
        {{C_ENTITIES,  175},   L"?AF"                                  },
        {{C_ENTITIES,  176},   L"?B0"                                  },
        {{C_ENTITIES,  177},   L"?B1"                                  },
        {{C_ENTITIES,  178},   L"?B2"                                  },
        {{C_ENTITIES,  179},   L"?B3"                                  },
        {{C_ENTITIES,  180},   L"?B4"                                  },
        {{C_ENTITIES,  181},   L"?B5"                                  },
        {{C_ENTITIES,  182},   L"?B6"                                  },
        {{C_ENTITIES,  183},   L"?B7"                                  },
        {{C_ENTITIES,  184},   L"?B8"                                  },
        {{C_ENTITIES,  185},   L"?B9"                                  },
        {{C_ENTITIES,  186},   L"?BA"                                  },
        {{C_ENTITIES,  187},   L"?BB"                                  },
        {{C_ENTITIES,  188},   L"?BC"                                  },
        {{C_ENTITIES,  189},   L"?BD"                                  },
        {{C_ENTITIES,  190},   L"?BE"                                  },
        {{C_ENTITIES,  191},   L"?BF"                                  },
        {{C_ENTITIES,  192},   L"EkeEke"                               },
        {{C_ENTITIES,  193},   L"Magic Sword"                          },
        {{C_ENTITIES,  194},   L"Ice Sword"                            },
        {{C_ENTITIES,  195},   L"Thunder Sword"                        },
        {{C_ENTITIES,  196},   L"Gaia Sword"                           },
        {{C_ENTITIES,  197},   L"Fireproof"                            },
        {{C_ENTITIES,  198},   L"Iron Boots"                           },
        {{C_ENTITIES,  199},   L"Healing Boots"                        },
        {{C_ENTITIES,  200},   L"Snow Spikes"                          },
        {{C_ENTITIES,  201},   L"Steel Breast"                         },
        {{C_ENTITIES,  202},   L"Chrome Breast"                        },
        {{C_ENTITIES,  203},   L"Shell Breast"                         },
        {{C_ENTITIES,  204},   L"Hyper Breast"                         },
        {{C_ENTITIES,  205},   L"Mars Stone"                           },
        {{C_ENTITIES,  206},   L"Moon Stone"                           },
        {{C_ENTITIES,  207},   L"Saturn Stone"                         },
        {{C_ENTITIES,  208},   L"Venus Stone"                          },
        {{C_ENTITIES,  209},   L"Awakening Book"                       },
        {{C_ENTITIES,  210},   L"Detox Grass"                          },
        {{C_ENTITIES,  211},   L"Gaia Statue"                          },
        {{C_ENTITIES,  212},   L"Golden Statue"                        },
        {{C_ENTITIES,  213},   L"Mind Repair"                          },
        {{C_ENTITIES,  214},   L"Casino Ticket"                        },
        {{C_ENTITIES,  215},   L"Axe Magic"                            },
        {{C_ENTITIES,  216},   L"Blue Ribbon"                          },
        {{C_ENTITIES,  217},   L"Buyer Card"                           },
        {{C_ENTITIES,  218},   L"Lantern"                              },
        {{C_ENTITIES,  219},   L"Garlic"                               },
        {{C_ENTITIES,  220},   L"Anti-Paralyze"                        },
        {{C_ENTITIES,  221},   L"Statue of Jypta"                      },
        {{C_ENTITIES,  222},   L"Sun Stone"                            },
        {{C_ENTITIES,  223},   L"Armlet"                               },
        {{C_ENTITIES,  224},   L"Einstein Whistle"                     },
        {{C_ENTITIES,  225},   L"Detox Book"                           },
        {{C_ENTITIES,  226},   L"AntiCurse"                            },
        {{C_ENTITIES,  227},   L"Record Book"                          },
        {{C_ENTITIES,  228},   L"Spell Book"                           },
        {{C_ENTITIES,  229},   L"Hotel Register"                       },
        {{C_ENTITIES,  230},   L"Island Map"                           },
        {{C_ENTITIES,  231},   L"Lithograph"                           },
        {{C_ENTITIES,  232},   L"Red Jewel"                            },
        {{C_ENTITIES,  233},   L"Pawn Ticket"                          },
        {{C_ENTITIES,  234},   L"Purple Jewel"                         },
        {{C_ENTITIES,  235},   L"Gola's Eye"                           },
        {{C_ENTITIES,  236},   L"Death Statue"                         },
        {{C_ENTITIES,  237},   L"Dahl"                                 },
        {{C_ENTITIES,  238},   L"Restoration"                          },
        {{C_ENTITIES,  239},   L"Logs"                                 },
        {{C_ENTITIES,  240},   L"Oracle Stone"                         },
        {{C_ENTITIES,  241},   L"Idol Stone"                           },
        {{C_ENTITIES,  242},   L"Key"                                  },
        {{C_ENTITIES,  243},   L"Safety Pass"                          },
        {{C_ENTITIES,  244},   L"No52"                                 },
        {{C_ENTITIES,  245},   L"Bell"                                 },
        {{C_ENTITIES,  246},   L"Shortcake"                            },
        {{C_ENTITIES,  247},   L"Gola's Nail"                          },
        {{C_ENTITIES,  248},   L"Gola's Horn"                          },
        {{C_ENTITIES,  249},   L"Gola's Fang"                          },
        {{C_ENTITIES,  250},   L"Broad Sword"                          },
        {{C_ENTITIES,  251},   L"Leather Breast"                       },
        {{C_ENTITIES,  252},   L"Leather Boots"                        },
        {{C_ENTITIES,  253},   L"None"                                 },
        {{C_ENTITIES,  254},   L"Lifestock"                            },
        {{C_ENTITIES,  255},   L"No63"                                 },
    };
}
