#include <landstalker/misc/include/DefaultLabels.h>
#include <landstalker/misc/include/Labels.h>

namespace DefaultLabels
{
	const std::map<std::pair<std::wstring, int>, std::wstring> DEFAULT_LABELS
	{
        {{L"rooms",     0},     L"000 Swamp shrine, floor 1"            },
        {{L"rooms",     1},     L"001 Swamp shrine, floor 1"            },
        {{L"rooms",     2},     L"002 Swamp shrine, floor 1"            },
        {{L"rooms",     3},     L"003 Swamp shrine, floor 1, stairs to floor 2"},
        {{L"rooms",     4},     L"004 Swamp shrine, floor 1"            },
        {{L"rooms",     5},     L"005 Swamp shrine, floor 1, boulders"  },
        {{L"rooms",     6},     L"006 Swamp shrine, floor 1"            },
        {{L"rooms",     7},     L"007 Swamp shrine, floor 1"            },
        {{L"rooms",     8},     L"008 Swamp shrine"                     },
        {{L"rooms",     9},     L"009 Swamp shrine"                     },
        {{L"rooms",     10},    L"010 Swamp shrine"                     },
        {{L"rooms",     11},    L"011 Swamp shrine"                     },
        {{L"rooms",     12},    L"012 Swamp shrine"                     },
        {{L"rooms",     13},    L"013 Swamp shrine"                     },
        {{L"rooms",     14},    L"014 Swamp shrine, floor 3"            },
        {{L"rooms",     15},    L"015 Swamp shrine, floor 1, boulders, empty"},
        {{L"rooms",     16},    L"016 Swamp shrine, floor 2, spiked boulders"},
        {{L"rooms",     17},    L"017 Swamp shrine, floor 2"            },
        {{L"rooms",     18},    L"018 Swamp shrine, floor 2, stairs to floor 3"},
        {{L"rooms",     19},    L"019 Swamp shrine"                     },
        {{L"rooms",     20},    L"020 Swamp shrine"                     },
        {{L"rooms",     21},    L"021 Swamp shrine, floor 3, spiked floor"},
        {{L"rooms",     22},    L"022 Swamp shrine"                     },
        {{L"rooms",     23},    L"023 Swamp shrine"                     },
        {{L"rooms",     24},    L"024 Swamp shrine"                     },
        {{L"rooms",     25},    L"025 Swamp shrine"                     },
        {{L"rooms",     26},    L"026 Swamp shrine"                     },
        {{L"rooms",     27},    L"027 Swamp shrine"                     },
        {{L"rooms",     28},    L"028 Swamp shrine"                     },
        {{L"rooms",     29},    L"029 Swamp shrine"                     },
        {{L"rooms",     30},    L"030 Swamp shrine"                     },
        {{L"rooms",     31},    L"031 Mercator castle ouside, main entrance"},
        {{L"rooms",     32},    L"032 Mercator castle, outside"         },
        {{L"rooms",     33},    L"033 Mercator castle, outside, west"   },
        {{L"rooms",     34},    L"034 Mercator castle, outside, west tower middle"},
        {{L"rooms",     35},    L"035 Mercator castle, outside, west tower top"},
        {{L"rooms",     36},    L"036 Mercator castle, basement entrance"},
        {{L"rooms",     37},    L"037 Mercator castle basement"         },
        {{L"rooms",     38},    L"038 Mercator castle basement"         },
        {{L"rooms",     39},    L"039 Mercator castle basement"         },
        {{L"rooms",     40},    L"040 Mercator castle basement"         },
        {{L"rooms",     41},    L"041 Mercator castle basement"         },
        {{L"rooms",     42},    L"042 Mercator castle basement"         },
        {{L"rooms",     43},    L"043 Mercator castle basement"         },
        {{L"rooms",     44},    L"044 Mercator castle basement, Moralis' cell"},
        {{L"rooms",     45},    L"045 Mercator castle basement, cell"   },
        {{L"rooms",     46},    L"046 Mercator castle basement"         },
        {{L"rooms",     47},    L"047 Mercator castle basement"         },
        {{L"rooms",     48},    L"048 Mercator castle basement"         },
        {{L"rooms",     49},    L"049 Mercator castle basement"         },
        {{L"rooms",     50},    L"050 Mercator castle basement"         },
        {{L"rooms",     51},    L"051 Mercator castle, throne"          },
        {{L"rooms",     52},    L"052 Mercator castle, throne"          },
        {{L"rooms",     53},    L"053 Mercator castle, throne"          },
        {{L"rooms",     54},    L"054 Mercator castle, throne"          },
        {{L"rooms",     55},    L"055 Mercator castle"                  },
        {{L"rooms",     56},    L"056 Mercator castle"                  },
        {{L"rooms",     57},    L"057 Mercator castle"                  },
        {{L"rooms",     58},    L"058 Mercator castle"                  },
        {{L"rooms",     59},    L"059 Mercator castle"                  },
        {{L"rooms",     60},    L"060 Mercator castle, main hall"       },
        {{L"rooms",     61},    L"061 Mercator castle, main hall"       },
        {{L"rooms",     62},    L"062 Mercator castle, main hall"       },
        {{L"rooms",     63},    L"063 Mercator castle, guards quaters"  },
        {{L"rooms",     64},    L"064 Mercator castle, guards quaters under attack"},
        {{L"rooms",     65},    L"065 Mercator castle"                  },
        {{L"rooms",     66},    L"066 Mercator castle"                  },
        {{L"rooms",     67},    L"067 Mercator castle"                  },
        {{L"rooms",     68},    L"068 Mercator castle, kitchen"         },
        {{L"rooms",     69},    L"069 Mercator castle, kitchen"         },
        {{L"rooms",     70},    L"070 Mercator castle"                  },
        {{L"rooms",     71},    L"071 Mercator castle"                  },
        {{L"rooms",     72},    L"072 Mercator castle"                  },
        {{L"rooms",     73},    L"073 Mercator castle, basement entrance"},
        {{L"rooms",     74},    L"074 Mercator castle, library"         },
        {{L"rooms",     75},    L"075 Mercator castle, library"         },
        {{L"rooms",     76},    L"076 Mercator castle"                  },
        {{L"rooms",     77},    L"077 Mercator castle"                  },
        {{L"rooms",     78},    L"078 Mercator castle, guards quaters"  },
        {{L"rooms",     79},    L"079 Mercator castle, guards quaters under attack"},
        {{L"rooms",     80},    L"080 Mercator castle"                  },
        {{L"rooms",     81},    L"081 Mercator castle"                  },
        {{L"rooms",     82},    L"082 Mercator castle"                  },
        {{L"rooms",     83},    L"083 Mercator castle"                  },
        {{L"rooms",     84},    L"084 Mercator castle, guards quaters under attack"},
        {{L"rooms",     85},    L"085 Mercator castle, Banquet hall"    },
        {{L"rooms",     86},    L"086 Mercator castle"                  },
        {{L"rooms",     87},    L"087 Mercator castle"                  },
        {{L"rooms",     88},    L"088 Mercator castle"                  },
        {{L"rooms",     89},    L"089 Mercator castle"                  },
        {{L"rooms",     90},    L"090 Mercator castle, guards quaters under attack"},
        {{L"rooms",     91},    L"091 Mercator castle"                  },
        {{L"rooms",     92},    L"092 Mercator castle"                  },
        {{L"rooms",     93},    L"093 Mercator castle"                  },
        {{L"rooms",     94},    L"094 Mercator castle"                  },
        {{L"rooms",     95},    L"095 Mercator castle"                  },
        {{L"rooms",     96},    L"096 Mercator castle"                  },
        {{L"rooms",     97},    L"097 Mercator castle"                  },
        {{L"rooms",     98},    L"098 Mercator castle"                  },
        {{L"rooms",     99},    L"099 Mercator castle, room"            },
        {{L"rooms",     100},   L"100 Mercator castle, Bathroom (entrance)"},
        {{L"rooms",     101},   L"101 Mercator castle, Bathroom"        },
        {{L"rooms",     102},   L"102 Mercator castle, Bathroom (empty)"},
        {{L"rooms",     103},   L"103 Mercator castle"                  },
        {{L"rooms",     104},   L"104 Mercator castle"                  },
        {{L"rooms",     105},   L"105 Mercator castle"                  },
        {{L"rooms",     106},   L"106 Mercator castle"                  },
        {{L"rooms",     107},   L"107 Mercator castle"                  },
        {{L"rooms",     108},   L"108 Mercator castle"                  },
        {{L"rooms",     109},   L"109 Mercator castle"                  },
        {{L"rooms",     110},   L"110 Mercator castle"                  },
        {{L"rooms",     111},   L"111 Treasure room (Nole)"             },
        {{L"rooms",     112},   L"112 Treasure room (Gola)"             },
        {{L"rooms",     113},   L"113 Treasure room (empty)"            },
        {{L"rooms",     114},   L"114 Nole palace, pillars"             },
        {{L"rooms",     115},   L"115 Nole palace"                      },
        {{L"rooms",     116},   L"116 Nole palace"                      },
        {{L"rooms",     117},   L"117 Nole palace, save"                },
        {{L"rooms",     118},   L"118 Nole palace"                      },
        {{L"rooms",     119},   L"119 Nole palace, stone warrior"       },
        {{L"rooms",     120},   L"120 Nole palace"                      },
        {{L"rooms",     121},   L"121 Nole palace, spinner"             },
        {{L"rooms",     122},   L"122 Nole palace"                      },
        {{L"rooms",     123},   L"123 Nole palace"                      },
        {{L"rooms",     124},   L"124 Nole palace"                      },
        {{L"rooms",     125},   L"125 Nole palace"                      },
        {{L"rooms",     126},   L"126 Nole palace"                      },
        {{L"rooms",     127},   L"127 Nole palace"                      },
        {{L"rooms",     128},   L"128 Nole palace"                      },
        {{L"rooms",     129},   L"129 Nole palace"                      },
        {{L"rooms",     130},   L"130 Nole palace"                      },
        {{L"rooms",     131},   L"131 Nole palace"                      },
        {{L"rooms",     132},   L"132 Nole palace"                      },
        {{L"rooms",     133},   L"133 Nole palace"                      },
        {{L"rooms",     134},   L"134 Nole palace"                      },
        {{L"rooms",     135},   L"135 Nole palace"                      },
        {{L"rooms",     136},   L"136 Nole palace"                      },
        {{L"rooms",     137},   L"137 Nole palace"                      },
        {{L"rooms",     138},   L"138 Nole palace"                      },
        {{L"rooms",     139},   L"139 Jypta Ruins"                      },
        {{L"rooms",     140},   L"140 Jypta Ruins"                      },
        {{L"rooms",     141},   L"141 Jypta Ruins"                      },
        {{L"rooms",     142},   L"142 Kalva harbor"                     },
        {{L"rooms",     143},   L"143 Bird"                             },
        {{L"rooms",     144},   L"144 Nole cave"                        },
        {{L"rooms",     145},   L"145 Nole cave"                        },
        {{L"rooms",     146},   L"146 Nole cave"                        },
        {{L"rooms",     147},   L"147 Nole cave"                        },
        {{L"rooms",     148},   L"148 Nole cave, outside"               },
        {{L"rooms",     149},   L"149 Nole cave"                        },
        {{L"rooms",     150},   L"150 Nole cave"                        },
        {{L"rooms",     151},   L"151 Nole cave"                        },
        {{L"rooms",     152},   L"152 Nole cave"                        },
        {{L"rooms",     153},   L"153 Nole cave"                        },
        {{L"rooms",     154},   L"154 Nole cave"                        },
        {{L"rooms",     155},   L"155 Nole cave"                        },
        {{L"rooms",     156},   L"156 Nole cave"                        },
        {{L"rooms",     157},   L"157 Nole cave"                        },
        {{L"rooms",     158},   L"158 Nole cave"                        },
        {{L"rooms",     159},   L"159 Nole cave"                        },
        {{L"rooms",     160},   L"160 Nole cave"                        },
        {{L"rooms",     161},   L"161 Nole cave"                        },
        {{L"rooms",     162},   L"162 Nole cave"                        },
        {{L"rooms",     163},   L"163 Nole cave"                        },
        {{L"rooms",     164},   L"164 Nole cave"                        },
        {{L"rooms",     165},   L"165 Nole cave"                        },
        {{L"rooms",     166},   L"166 Nole cave"                        },
        {{L"rooms",     167},   L"167 Nole cave, river"                 },
        {{L"rooms",     168},   L"168 Nole cave, river"                 },
        {{L"rooms",     169},   L"169 Nole cave, river"                 },
        {{L"rooms",     170},   L"170 Nole cave"                        },
        {{L"rooms",     171},   L"171 Nole cave"                        },
        {{L"rooms",     172},   L"172 Nole cave"                        },
        {{L"rooms",     173},   L"173 Gemstone room"                    },
        {{L"rooms",     174},   L"174 Waterfall shrine"                 },
        {{L"rooms",     175},   L"175 Waterfall shrine"                 },
        {{L"rooms",     176},   L"176 Waterfall shrine"                 },
        {{L"rooms",     177},   L"177 Waterfall shrine"                 },
        {{L"rooms",     178},   L"178 Waterfall shrine"                 },
        {{L"rooms",     179},   L"179 Waterfall shrine"                 },
        {{L"rooms",     180},   L"180 Waterfall shrine"                 },
        {{L"rooms",     181},   L"181 Waterfall shrine"                 },
        {{L"rooms",     182},   L"182 Waterfall shrine"                 },
        {{L"rooms",     183},   L"183 Thieves' hideout (Outside entrance)"},
        {{L"rooms",     184},   L"184 Thieves' hideout"                 },
        {{L"rooms",     185},   L"185 Thieves' hideout"                 },
        {{L"rooms",     186},   L"186 Thieves' hideout"                 },
        {{L"rooms",     187},   L"187 Thieves' hideout"                 },
        {{L"rooms",     188},   L"188 Thieves' hideout"                 },
        {{L"rooms",     189},   L"189 Thieves' hideout"                 },
        {{L"rooms",     190},   L"190 Thieves' hideout"                 },
        {{L"rooms",     191},   L"191 Thieves' hideout, cell"           },
        {{L"rooms",     192},   L"192 Thieves' hideout"                 },
        {{L"rooms",     193},   L"193 Thieves' hideout"                 },
        {{L"rooms",     194},   L"194 Thieves' hideout"                 },
        {{L"rooms",     195},   L"195 Thieves' hideout"                 },
        {{L"rooms",     196},   L"196 Thieves' hideout"                 },
        {{L"rooms",     197},   L"197 Thieves' hideout"                 },
        {{L"rooms",     198},   L"198 Thieves' hideout"                 },
        {{L"rooms",     199},   L"199 Thieves' hideout"                 },
        {{L"rooms",     200},   L"200 Thieves' hideout"                 },
        {{L"rooms",     201},   L"201 Thieves' hideout"                 },
        {{L"rooms",     202},   L"202 Thieves' hideout"                 },
        {{L"rooms",     203},   L"203 Thieves' hideout"                 },
        {{L"rooms",     204},   L"204 Thieves' hideout"                 },
        {{L"rooms",     205},   L"205 Thieves' hideout"                 },
        {{L"rooms",     206},   L"206 Thieves' hideout"                 },
        {{L"rooms",     207},   L"207 Thieves' hideout"                 },
        {{L"rooms",     208},   L"208 Thieves' hideout"                 },
        {{L"rooms",     209},   L"209 Thieves' hideout"                 },
        {{L"rooms",     210},   L"210 Thieves' hideout"                 },
        {{L"rooms",     211},   L"211 Thieves' hideout"                 },
        {{L"rooms",     212},   L"212 Thieves' hideout"                 },
        {{L"rooms",     213},   L"213 Thieves' hideout"                 },
        {{L"rooms",     214},   L"214 Thieves' hideout"                 },
        {{L"rooms",     215},   L"215 Thieves' hideout"                 },
        {{L"rooms",     216},   L"216 Thieves' hideout"                 },
        {{L"rooms",     217},   L"217 Thieves' hideout"                 },
        {{L"rooms",     218},   L"218 Thieves' hideout"                 },
        {{L"rooms",     219},   L"219 Thieves' hideout, save"           },
        {{L"rooms",     220},   L"220 Thieves' hideout, save"           },
        {{L"rooms",     221},   L"221 Thieves' hideout"                 },
        {{L"rooms",     222},   L"222 Thieves' hideout"                 },
        {{L"rooms",     223},   L"223 Thieves' hideout"                 },
        {{L"rooms",     224},   L"224 Thieves' hideout"                 },
        {{L"rooms",     225},   L"225 Thieves' hideout"                 },
        {{L"rooms",     226},   L"226 Thieves' hideout, cliff"          },
        {{L"rooms",     227},   L"227 Verla Mine"                       },
        {{L"rooms",     228},   L"228 Verla Mine"                       },
        {{L"rooms",     229},   L"229 Verla Mine"                       },
        {{L"rooms",     230},   L"230 Verla Mine"                       },
        {{L"rooms",     231},   L"231 Verla Mine"                       },
        {{L"rooms",     232},   L"232 Verla Mine"                       },
        {{L"rooms",     233},   L"233 Verla Mine"                       },
        {{L"rooms",     234},   L"234 Verla Mine"                       },
        {{L"rooms",     235},   L"235 Verla Mine"                       },
        {{L"rooms",     236},   L"236 Verla Mine"                       },
        {{L"rooms",     237},   L"237 Verla Mine"                       },
        {{L"rooms",     238},   L"238 Verla Mine"                       },
        {{L"rooms",     239},   L"239 Verla Mine"                       },
        {{L"rooms",     240},   L"240 Verla Mine"                       },
        {{L"rooms",     241},   L"241 Verla Mine"                       },
        {{L"rooms",     242},   L"242 Verla Mine"                       },
        {{L"rooms",     243},   L"243 Verla Mine"                       },
        {{L"rooms",     244},   L"244 Verla Mine"                       },
        {{L"rooms",     245},   L"245 Verla Mine"                       },
        {{L"rooms",     246},   L"246 Verla Mine"                       },
        {{L"rooms",     247},   L"247 Verla Mine"                       },
        {{L"rooms",     248},   L"248 Verla Mine"                       },
        {{L"rooms",     249},   L"249 Verla Mine"                       },
        {{L"rooms",     250},   L"250 Verla Mine"                       },
        {{L"rooms",     251},   L"251 Verla Mine"                       },
        {{L"rooms",     252},   L"252 Verla Mine"                       },
        {{L"rooms",     253},   L"253 Verla Mine"                       },
        {{L"rooms",     254},   L"254 Verla Mine"                       },
        {{L"rooms",     255},   L"255 Verla Mine"                       },
        {{L"rooms",     256},   L"256 Verla Mine"                       },
        {{L"rooms",     257},   L"257 Verla Mine"                       },
        {{L"rooms",     258},   L"258 Verla Mine"                       },
        {{L"rooms",     259},   L"259 Verla Mine"                       },
        {{L"rooms",     260},   L"260 Verla Mine"                       },
        {{L"rooms",     261},   L"261 Verla Mine"                       },
        {{L"rooms",     262},   L"262 Verla Mine"                       },
        {{L"rooms",     263},   L"263 Verla Mine"                       },
        {{L"rooms",     264},   L"264 Verla Mine"                       },
        {{L"rooms",     265},   L"265 Verla Mine"                       },
        {{L"rooms",     266},   L"266 Verla Mine"                       },
        {{L"rooms",     267},   L"267 Verla Mine"                       },
        {{L"rooms",     268},   L"268 Verla Mine"                       },
        {{L"rooms",     269},   L"269 Verla Mine"                       },
        {{L"rooms",     270},   L"270 Destel well"                      },
        {{L"rooms",     271},   L"271 Destel well"                      },
        {{L"rooms",     272},   L"272 Destel well"                      },
        {{L"rooms",     273},   L"273 Destel well"                      },
        {{L"rooms",     274},   L"274 Destel well"                      },
        {{L"rooms",     275},   L"275 Destel well"                      },
        {{L"rooms",     276},   L"276 Destel well"                      },
        {{L"rooms",     277},   L"277 Destel well"                      },
        {{L"rooms",     278},   L"278 Destel well"                      },
        {{L"rooms",     279},   L"279 Destel well"                      },
        {{L"rooms",     280},   L"280 Destel well"                      },
        {{L"rooms",     281},   L"281 Destel well"                      },
        {{L"rooms",     282},   L"282 Destel well"                      },
        {{L"rooms",     283},   L"283 Destel well"                      },
        {{L"rooms",     284},   L"284 Destel well"                      },
        {{L"rooms",     285},   L"285 Destel well"                      },
        {{L"rooms",     286},   L"286 Destel well"                      },
        {{L"rooms",     287},   L"287 Destel well"                      },
        {{L"rooms",     288},   L"288 Destel well"                      },
        {{L"rooms",     289},   L"289 Destel well"                      },
        {{L"rooms",     290},   L"290 Destel well"                      },
        {{L"rooms",     291},   L"291 Lake Shrine"                      },
        {{L"rooms",     292},   L"292 Lake Shrine"                      },
        {{L"rooms",     293},   L"293 Lake Shrine"                      },
        {{L"rooms",     294},   L"294 Lake Shrine"                      },
        {{L"rooms",     295},   L"295 Lake Shrine"                      },
        {{L"rooms",     296},   L"296 Lake Shrine"                      },
        {{L"rooms",     297},   L"297 Lake Shrine"                      },
        {{L"rooms",     298},   L"298 Lake Shrine"                      },
        {{L"rooms",     299},   L"299 Lake Shrine"                      },
        {{L"rooms",     300},   L"300 Lake Shrine"                      },
        {{L"rooms",     301},   L"301 Lake Shrine"                      },
        {{L"rooms",     302},   L"302 Lake Shrine"                      },
        {{L"rooms",     303},   L"303 Lake Shrine"                      },
        {{L"rooms",     304},   L"304 Lake Shrine"                      },
        {{L"rooms",     305},   L"305 Lake Shrine"                      },
        {{L"rooms",     306},   L"306 Lake Shrine"                      },
        {{L"rooms",     307},   L"307 Lake Shrine"                      },
        {{L"rooms",     308},   L"308 Lake Shrine"                      },
        {{L"rooms",     309},   L"309 Lake Shrine"                      },
        {{L"rooms",     310},   L"310 Lake Shrine"                      },
        {{L"rooms",     311},   L"311 Lake Shrine"                      },
        {{L"rooms",     312},   L"312 Lake Shrine"                      },
        {{L"rooms",     313},   L"313 Lake Shrine"                      },
        {{L"rooms",     314},   L"314 Lake Shrine"                      },
        {{L"rooms",     315},   L"315 Lake Shrine"                      },
        {{L"rooms",     316},   L"316 Lake Shrine"                      },
        {{L"rooms",     317},   L"317 Lake Shrine"                      },
        {{L"rooms",     318},   L"318 Lake Shrine"                      },
        {{L"rooms",     319},   L"319 Lake Shrine"                      },
        {{L"rooms",     320},   L"320 Lake Shrine"                      },
        {{L"rooms",     321},   L"321 Lake Shrine"                      },
        {{L"rooms",     322},   L"322 Lake Shrine"                      },
        {{L"rooms",     323},   L"323 Lake Shrine"                      },
        {{L"rooms",     324},   L"324 Lake Shrine"                      },
        {{L"rooms",     325},   L"325 Lake Shrine"                      },
        {{L"rooms",     326},   L"326 Lake Shrine"                      },
        {{L"rooms",     327},   L"327 Lake Shrine"                      },
        {{L"rooms",     328},   L"328 Lake Shrine"                      },
        {{L"rooms",     329},   L"329 Lake Shrine"                      },
        {{L"rooms",     330},   L"330 Lake Shrine"                      },
        {{L"rooms",     331},   L"331 Lake Shrine"                      },
        {{L"rooms",     332},   L"332 Lake Shrine"                      },
        {{L"rooms",     333},   L"333 Lake Shrine"                      },
        {{L"rooms",     334},   L"334 Lake Shrine"                      },
        {{L"rooms",     335},   L"335 Lake Shrine"                      },
        {{L"rooms",     336},   L"336 Lake Shrine"                      },
        {{L"rooms",     337},   L"337 Lake Shrine"                      },
        {{L"rooms",     338},   L"338 Lake Shrine"                      },
        {{L"rooms",     339},   L"339 Lake Shrine"                      },
        {{L"rooms",     340},   L"340 Lake Shrine"                      },
        {{L"rooms",     341},   L"341 Lake Shrine"                      },
        {{L"rooms",     342},   L"342 Lake Shrine"                      },
        {{L"rooms",     343},   L"343 Lake Shrine"                      },
        {{L"rooms",     344},   L"344 Lake Shrine"                      },
        {{L"rooms",     345},   L"345 Lake Shrine"                      },
        {{L"rooms",     346},   L"346 Lake Shrine"                      },
        {{L"rooms",     347},   L"347 Lake Shrine"                      },
        {{L"rooms",     348},   L"348 Lake Shrine"                      },
        {{L"rooms",     349},   L"349 Lake Shrine"                      },
        {{L"rooms",     350},   L"350 Lake Shrine"                      },
        {{L"rooms",     351},   L"351 Lake Shrine"                      },
        {{L"rooms",     352},   L"352 Lake Shrine"                      },
        {{L"rooms",     353},   L"353 Lake Shrine"                      },
        {{L"rooms",     354},   L"354 Lake Shrine"                      },
        {{L"rooms",     355},   L"355 Nole's labyrinth"                 },
        {{L"rooms",     356},   L"356 Nole's labyrinth"                 },
        {{L"rooms",     357},   L"357 Nole's labyrinth"                 },
        {{L"rooms",     358},   L"358 Nole's labyrinth"                 },
        {{L"rooms",     359},   L"359 Nole's labyrinth"                 },
        {{L"rooms",     360},   L"360 Nole's labyrinth"                 },
        {{L"rooms",     361},   L"361 Nole's labyrinth"                 },
        {{L"rooms",     362},   L"362 Nole's labyrinth"                 },
        {{L"rooms",     363},   L"363 Nole's labyrinth"                 },
        {{L"rooms",     364},   L"364 Nole's labyrinth"                 },
        {{L"rooms",     365},   L"365 Nole's labyrinth"                 },
        {{L"rooms",     366},   L"366 Nole's labyrinth"                 },
        {{L"rooms",     367},   L"367 Nole's labyrinth"                 },
        {{L"rooms",     368},   L"368 Nole's labyrinth"                 },
        {{L"rooms",     369},   L"369 Nole's labyrinth"                 },
        {{L"rooms",     370},   L"370 Nole's labyrinth"                 },
        {{L"rooms",     371},   L"371 Nole's labyrinth"                 },
        {{L"rooms",     372},   L"372 Nole's labyrinth"                 },
        {{L"rooms",     373},   L"373 Nole's labyrinth"                 },
        {{L"rooms",     374},   L"374 Nole's labyrinth"                 },
        {{L"rooms",     375},   L"375 Nole's labyrinth"                 },
        {{L"rooms",     376},   L"376 Nole's labyrinth"                 },
        {{L"rooms",     377},   L"377 Nole's labyrinth"                 },
        {{L"rooms",     378},   L"378 Nole's labyrinth"                 },
        {{L"rooms",     379},   L"379 Nole's labyrinth"                 },
        {{L"rooms",     380},   L"380 Nole's labyrinth"                 },
        {{L"rooms",     381},   L"381 Nole's labyrinth"                 },
        {{L"rooms",     382},   L"382 Nole's labyrinth"                 },
        {{L"rooms",     383},   L"383 Nole's labyrinth"                 },
        {{L"rooms",     384},   L"384 Nole's labyrinth"                 },
        {{L"rooms",     385},   L"385 Nole's labyrinth"                 },
        {{L"rooms",     386},   L"386 Nole's labyrinth"                 },
        {{L"rooms",     387},   L"387 Nole's labyrinth"                 },
        {{L"rooms",     388},   L"388 Nole's labyrinth"                 },
        {{L"rooms",     389},   L"389 Nole's labyrinth"                 },
        {{L"rooms",     390},   L"390 Nole's labyrinth"                 },
        {{L"rooms",     391},   L"391 Nole's labyrinth"                 },
        {{L"rooms",     392},   L"392 Nole's labyrinth"                 },
        {{L"rooms",     393},   L"393 Nole's labyrinth"                 },
        {{L"rooms",     394},   L"394 Nole's labyrinth"                 },
        {{L"rooms",     395},   L"395 Nole's labyrinth"                 },
        {{L"rooms",     396},   L"396 Nole's labyrinth"                 },
        {{L"rooms",     397},   L"397 Nole's labyrinth"                 },
        {{L"rooms",     398},   L"398 Nole's labyrinth"                 },
        {{L"rooms",     399},   L"399 Nole's labyrinth"                 },
        {{L"rooms",     400},   L"400 Nole's labyrinth"                 },
        {{L"rooms",     401},   L"401 Nole's labyrinth"                 },
        {{L"rooms",     402},   L"402 Nole's labyrinth"                 },
        {{L"rooms",     403},   L"403 Nole's labyrinth"                 },
        {{L"rooms",     404},   L"404 Nole's labyrinth"                 },
        {{L"rooms",     405},   L"405 Nole's labyrinth"                 },
        {{L"rooms",     406},   L"406 Nole's labyrinth"                 },
        {{L"rooms",     407},   L"407 Nole's labyrinth"                 },
        {{L"rooms",     408},   L"408 Nole's labyrinth"                 },
        {{L"rooms",     409},   L"409 Nole's labyrinth"                 },
        {{L"rooms",     410},   L"410 Nole's labyrinth"                 },
        {{L"rooms",     411},   L"411 Nole's labyrinth"                 },
        {{L"rooms",     412},   L"412 Nole's labyrinth"                 },
        {{L"rooms",     413},   L"413 Nole's labyrinth"                 },
        {{L"rooms",     414},   L"414 Nole's labyrinth"                 },
        {{L"rooms",     415},   L"415 Nole's labyrinth"                 },
        {{L"rooms",     416},   L"416 Nole's labyrinth"                 },
        {{L"rooms",     417},   L"417 Nole's labyrinth"                 },
        {{L"rooms",     418},   L"418 Nole's labyrinth"                 },
        {{L"rooms",     419},   L"419 Nole's labyrinth"                 },
        {{L"rooms",     420},   L"420 Nole's labyrinth"                 },
        {{L"rooms",     421},   L"421 Nole palace, stairs"              },
        {{L"rooms",     422},   L"422 Nole's labyrinth"                 },
        {{L"rooms",     423},   L"423 Nole's labyrinth"                 },
        {{L"rooms",     424},   L"424 Road"                             },
        {{L"rooms",     425},   L"425 Road"                             },
        {{L"rooms",     426},   L"426 Road, ouside of waterfall shrine" },
        {{L"rooms",     427},   L"427 Road"                             },
        {{L"rooms",     428},   L"428 Road"                             },
        {{L"rooms",     429},   L"429 Cliff"                            },
        {{L"rooms",     430},   L"430 Cliff"                            },
        {{L"rooms",     431},   L"431 Swamp"                            },
        {{L"rooms",     432},   L"432 Swamp"                            },
        {{L"rooms",     433},   L"433 Swamp, shrine outside"            },
        {{L"rooms",     434},   L"434 Road"                             },
        {{L"rooms",     435},   L"435 Road"                             },
        {{L"rooms",     436},   L"436 Swamp"                            },
        {{L"rooms",     437},   L"437 Road"                             },
        {{L"rooms",     438},   L"438 Road"                             },
        {{L"rooms",     439},   L"439 Road"                             },
        {{L"rooms",     440},   L"440 Road"                             },
        {{L"rooms",     441},   L"441 Helga's hut, outside"             },
        {{L"rooms",     442},   L"442 Lone house"                       },
        {{L"rooms",     443},   L"443 Swamp"                            },
        {{L"rooms",     444},   L"444 Swamp"                            },
        {{L"rooms",     445},   L"445 Road"                             },
        {{L"rooms",     446},   L"446 Road"                             },
        {{L"rooms",     447},   L"447 Road"                             },
        {{L"rooms",     448},   L"448 Road"                             },
        {{L"rooms",     449},   L"449 Road"                             },
        {{L"rooms",     450},   L"450 Road"                             },
        {{L"rooms",     451},   L"451 Road"                             },
        {{L"rooms",     452},   L"452 Road"                             },
        {{L"rooms",     453},   L"453 Road"                             },
        {{L"rooms",     454},   L"454 Mercator gate"                    },
        {{L"rooms",     455},   L"455 Road"                             },
        {{L"rooms",     456},   L"456 Road"                             },
        {{L"rooms",     457},   L"457 Road"                             },
        {{L"rooms",     458},   L"458 Road"                             },
        {{L"rooms",     459},   L"459 Road"                             },
        {{L"rooms",     460},   L"460 Road"                             },
        {{L"rooms",     461},   L"461 Road, ouside of Friday's village" },
        {{L"rooms",     462},   L"462 Friday's village"                 },
        {{L"rooms",     463},   L"463 Road"                             },
        {{L"rooms",     464},   L"464 Road"                             },
        {{L"rooms",     465},   L"465 Road"                             },
        {{L"rooms",     466},   L"466 Underground passage"              },
        {{L"rooms",     467},   L"467 Road"                             },
        {{L"rooms",     468},   L"468 Road"                             },
        {{L"rooms",     469},   L"469 Road"                             },
        {{L"rooms",     470},   L"470 Road"                             },
        {{L"rooms",     471},   L"471 Underground passage"              },
        {{L"rooms",     472},   L"472 Road"                             },
        {{L"rooms",     473},   L"473 Road"                             },
        {{L"rooms",     474},   L"474 Road"                             },
        {{L"rooms",     475},   L"475 Mir tower, outside"               },
        {{L"rooms",     476},   L"476 Road"                             },
        {{L"rooms",     477},   L"477 Soldier's house"                  },
        {{L"rooms",     478},   L"478 Road, waterfall"                  },
        {{L"rooms",     479},   L"479 Helga's hut"                      },
        {{L"rooms",     480},   L"480 Helga's hut, entrance"            },
        {{L"rooms",     481},   L"481 Mountain"                         },
        {{L"rooms",     482},   L"482 Mountain"                         },
        {{L"rooms",     483},   L"483 Mountain"                         },
        {{L"rooms",     484},   L"484 Mountain"                         },
        {{L"rooms",     485},   L"485 Mountain"                         },
        {{L"rooms",     486},   L"486 Mountain, save"                   },
        {{L"rooms",     487},   L"487 Mountain"                         },
        {{L"rooms",     488},   L"488 Road, lake"                       },
        {{L"rooms",     489},   L"489 Road, hut"                        },
        {{L"rooms",     490},   L"490 Road"                             },
        {{L"rooms",     491},   L"491 Inside hut"                       },
        {{L"rooms",     492},   L"492 Mountain"                         },
        {{L"rooms",     493},   L"493 Dock with boat"                   },
        {{L"rooms",     494},   L"494 Dock with boat"                   },
        {{L"rooms",     495},   L"495 Dock with boat"                   },
        {{L"rooms",     496},   L"496 Dock"                             },
        {{L"rooms",     497},   L"497 Boat"                             },
        {{L"rooms",     498},   L"498 Tall waterfall, cutscene"         },
        {{L"rooms",     499},   L"499 Inside hut"                       },
        {{L"rooms",     500},   L"500 Road"                             },
        {{L"rooms",     501},   L"501 Road"                             },
        {{L"rooms",     502},   L"502 Road"                             },
        {{L"rooms",     503},   L"503 Road"                             },
        {{L"rooms",     504},   L"504 Road"                             },
        {{L"rooms",     505},   L"505 Road"                             },
        {{L"rooms",     506},   L"506 Road"                             },
        {{L"rooms",     507},   L"507 Road"                             },
        {{L"rooms",     508},   L"508 Road"                             },
        {{L"rooms",     509},   L"509 Road"                             },
        {{L"rooms",     510},   L"510 Tibor, outside"                   },
        {{L"rooms",     511},   L"511 Tibor, outside"                   },
        {{L"rooms",     512},   L"512 Tibor, outside"                   },
        {{L"rooms",     513},   L"513 Tibor, outside"                   },
        {{L"rooms",     514},   L"514 Road"                             },
        {{L"rooms",     515},   L"515 Road"                             },
        {{L"rooms",     516},   L"516 Underground passageway"           },
        {{L"rooms",     517},   L"517 Waterfall shop"                   },
        {{L"rooms",     519},   L"519 Road"                             },
        {{L"rooms",     520},   L"520 Road"                             },
        {{L"rooms",     521},   L"521 Road"                             },
        {{L"rooms",     522},   L"522 Verla mine, save"                 },
        {{L"rooms",     523},   L"523 Lake"                             },
        {{L"rooms",     524},   L"524 Lake, lava"                       },
        {{L"rooms",     525},   L"525 Lake"                             },
        {{L"rooms",     526},   L"526 Lake, ouside of shrine"           },
        {{L"rooms",     527},   L"527 Inside hut, empty"                },
        {{L"rooms",     528},   L"528 Road"                             },
        {{L"rooms",     529},   L"529 Road, pit"                        },
        {{L"rooms",     530},   L"530 Road"                             },
        {{L"rooms",     531},   L"531 Road"                             },
        {{L"rooms",     532},   L"532 Underground passageway"           },
        {{L"rooms",     533},   L"533 Tibor, outside"                   },
        {{L"rooms",     534},   L"534 Tibor, outside"                   },
        {{L"rooms",     535},   L"535 Tibor, outside"                   },
        {{L"rooms",     536},   L"536 Tibor, outside"                   },
        {{L"rooms",     537},   L"537 Tibor, outside"                   },
        {{L"rooms",     538},   L"538 Tibor, outside"                   },
        {{L"rooms",     539},   L"539 Tibor, outside"                   },
        {{L"rooms",     540},   L"540 Road"                             },
        {{L"rooms",     541},   L"541 Road"                             },
        {{L"rooms",     542},   L"542 Road"                             },
        {{L"rooms",     543},   L"543 Dock"                             },
        {{L"rooms",     544},   L"544 Dock"                             },
        {{L"rooms",     545},   L"545 Outside"                          },
        {{L"rooms",     546},   L"546 Mountain, underground"            },
        {{L"rooms",     547},   L"547 Mountain, underground"            },
        {{L"rooms",     548},   L"548 Mountain, underground"            },
        {{L"rooms",     549},   L"549 Mountain, underground"            },
        {{L"rooms",     550},   L"550 Mountain, underground"            },
        {{L"rooms",     551},   L"551 Mountain, underground"            },
        {{L"rooms",     552},   L"552 Mountain, underground"            },
        {{L"rooms",     553},   L"553 Mountain, underground"            },
        {{L"rooms",     554},   L"554 Mountain, underground"            },
        {{L"rooms",     555},   L"555 Mountain, underground"            },
        {{L"rooms",     556},   L"556 Green maze"                       },
        {{L"rooms",     557},   L"557 Green maze"                       },
        {{L"rooms",     558},   L"558 Green maze"                       },
        {{L"rooms",     559},   L"559 Green maze"                       },
        {{L"rooms",     560},   L"560 Green Maze"                       },
        {{L"rooms",     561},   L"561 Green Maze"                       },
        {{L"rooms",     562},   L"562 Green Maze"                       },
        {{L"rooms",     563},   L"563 Green Maze"                       },
        {{L"rooms",     564},   L"564 Green Maze"                       },
        {{L"rooms",     565},   L"565 Green Maze"                       },
        {{L"rooms",     566},   L"566 Green Maze"                       },
        {{L"rooms",     567},   L"567 Green Maze"                       },
        {{L"rooms",     568},   L"568 Green Maze"                       },
        {{L"rooms",     569},   L"569 Green Maze"                       },
        {{L"rooms",     570},   L"570 Green Maze"                       },
        {{L"rooms",     571},   L"571 Green maze"                       },
        {{L"rooms",     572},   L"572 Green maze"                       },
        {{L"rooms",     573},   L"573 Green maze"                       },
        {{L"rooms",     574},   L"574 Green maze"                       },
        {{L"rooms",     575},   L"575 Green maze"                       },
        {{L"rooms",     576},   L"576 Green maze"                       },
        {{L"rooms",     577},   L"577 Green maze"                       },
        {{L"rooms",     578},   L"578 Green maze"                       },
        {{L"rooms",     579},   L"579 Green maze"                       },
        {{L"rooms",     580},   L"580 Green maze"                       },
        {{L"rooms",     581},   L"581 Green maze"                       },
        {{L"rooms",     582},   L"582 Green maze"                       },
        {{L"rooms",     583},   L"583 Green maze"                       },
        {{L"rooms",     584},   L"584 Green maze"                       },
        {{L"rooms",     585},   L"585 Green maze"                       },
        {{L"rooms",     586},   L"586 Green maze"                       },
        {{L"rooms",     587},   L"587 Green maze"                       },
        {{L"rooms",     588},   L"588 Green maze"                       },
        {{L"rooms",     589},   L"589 Green maze"                       },
        {{L"rooms",     590},   L"590 Green maze"                       },
        {{L"rooms",     591},   L"591 Green maze"                       },
        {{L"rooms",     592},   L"592 Massan village, outside"          },
        {{L"rooms",     593},   L"593 Massan village, hut"              },
        {{L"rooms",     594},   L"594 Massan village, hut"              },
        {{L"rooms",     595},   L"595 Massan village, hut"              },
        {{L"rooms",     596},   L"596 Massan village, shop"             },
        {{L"rooms",     597},   L"597 Massan village, church"           },
        {{L"rooms",     598},   L"598 Massan village, inn"              },
        {{L"rooms",     599},   L"599 Massan village, hut"              },
        {{L"rooms",     600},   L"600 Massan village, inn, second floor"},
        {{L"rooms",     601},   L"601 Gumi village, stake"              },
        {{L"rooms",     602},   L"602 Gumi village"                     },
        {{L"rooms",     603},   L"603 Gumi village"                     },
        {{L"rooms",     604},   L"604 Gumi village, hut"                },
        {{L"rooms",     605},   L"605 Gumi village, hut"                },
        {{L"rooms",     606},   L"606 Gumi village, hut"                },
        {{L"rooms",     607},   L"607 Gumi village, church"             },
        {{L"rooms",     608},   L"608 Gumi village, inn first floor"    },
        {{L"rooms",     609},   L"609 Gumi village, inn secoond floor"  },
        {{L"rooms",     610},   L"610 Ryuma"                            },
        {{L"rooms",     611},   L"611 Ryuma"                            },
        {{L"rooms",     612},   L"612 Ryuma, lighthouse"                },
        {{L"rooms",     613},   L"613 Ryuma"                            },
        {{L"rooms",     614},   L"614 Ryuma, church"                    },
        {{L"rooms",     615},   L"615 Ryuma, shop"                      },
        {{L"rooms",     616},   L"616 Ryuma"                            },
        {{L"rooms",     617},   L"617 Ryuma"                            },
        {{L"rooms",     618},   L"618 Ryuma"                            },
        {{L"rooms",     619},   L"619 Ryuma"                            },
        {{L"rooms",     620},   L"620 Ryuma"                            },
        {{L"rooms",     621},   L"621 Ryuma"                            },
        {{L"rooms",     622},   L"622 Ryuma"                            },
        {{L"rooms",     623},   L"623 Ryuma, inn"                       },
        {{L"rooms",     624},   L"624 Ryuma, inn"                       },
        {{L"rooms",     625},   L"625 Ryuma, lighthouse stairs"         },
        {{L"rooms",     626},   L"626 Ryuma, lighthouse stairs"         },
        {{L"rooms",     627},   L"627 Ryuma, lighthouse top"            },
        {{L"rooms",     628},   L"628 Ryuma, lighthouse top (night)"    },
        {{L"rooms",     629},   L"629 Ryuma, lighthouse top"            },
        {{L"rooms",     630},   L"630 Mercator"                         },
        {{L"rooms",     631},   L"631 Mercator"                         },
        {{L"rooms",     632},   L"632 Mercator"                         },
        {{L"rooms",     633},   L"633 Mercator"                         },
        {{L"rooms",     634},   L"634 Mercator"                         },
        {{L"rooms",     635},   L"635 Mercator"                         },
        {{L"rooms",     636},   L"636 Mercator"                         },
        {{L"rooms",     637},   L"637 Mercator"                         },
        {{L"rooms",     638},   L"638 Mercator"                         },
        {{L"rooms",     639},   L"639 Mercator"                         },
        {{L"rooms",     640},   L"640 Mercator"                         },
        {{L"rooms",     641},   L"641 Mercator harbor"                  },
        {{L"rooms",     642},   L"642 Mercator harbor"                  },
        {{L"rooms",     643},   L"643 Mercator harbor"                  },
        {{L"rooms",     644},   L"644 Mercator harbor"                  },
        {{L"rooms",     645},   L"645 Underground passage"              },
        {{L"rooms",     646},   L"646 Crypt"                            },
        {{L"rooms",     647},   L"647 Crypt"                            },
        {{L"rooms",     648},   L"648 Crypt"                            },
        {{L"rooms",     649},   L"649 Crypt"                            },
        {{L"rooms",     650},   L"650 Crypt"                            },
        {{L"rooms",     651},   L"651 Crypt, mummy's room"              },
        {{L"rooms",     652},   L"652 Crypt"                            },
        {{L"rooms",     653},   L"653 Crypt"                            },
        {{L"rooms",     654},   L"654 Crypt"                            },
        {{L"rooms",     655},   L"655 Crypt"                            },
        {{L"rooms",     656},   L"656 Crypt"                            },
        {{L"rooms",     657},   L"657 Crypt"                            },
        {{L"rooms",     658},   L"658 Crypt"                            },
        {{L"rooms",     659},   L"659 Crypt"                            },
        {{L"rooms",     660},   L"660 Mercator"                         },
        {{L"rooms",     661},   L"661 Mercator"                         },
        {{L"rooms",     662},   L"662 Mercator"                         },
        {{L"rooms",     663},   L"663 Casino, corridor"                 },
        {{L"rooms",     664},   L"664 Casino, roulette"                 },
        {{L"rooms",     665},   L"665 Casino, sprint race"              },
        {{L"rooms",     666},   L"666 Casino, chicken"                  },
        {{L"rooms",     667},   L"667 Mercator"                         },
        {{L"rooms",     668},   L"668 Mercator"                         },
        {{L"rooms",     669},   L"669 Mercator"                         },
        {{L"rooms",     670},   L"670 Mercator"                         },
        {{L"rooms",     671},   L"671 Mercator"                         },
        {{L"rooms",     672},   L"672 Mercator, throw game"             },
        {{L"rooms",     673},   L"673 Mercator"                         },
        {{L"rooms",     674},   L"674 Mercator"                         },
        {{L"rooms",     675},   L"675 Mercator"                         },
        {{L"rooms",     676},   L"676 Mercator"                         },
        {{L"rooms",     677},   L"677 Mercator"                         },
        {{L"rooms",     678},   L"678 Mercator"                         },
        {{L"rooms",     679},   L"679 Mercator"                         },
        {{L"rooms",     680},   L"680 Madam yard's"                     },
        {{L"rooms",     681},   L"681 Mercator prison"                  },
        {{L"rooms",     682},   L"682 Mercator prison"                  },
        {{L"rooms",     683},   L"683 Mercator"                         },
        {{L"rooms",     684},   L"684 Mercator"                         },
        {{L"rooms",     685},   L"685 Mercator"                         },
        {{L"rooms",     686},   L"686 Mercator"                         },
        {{L"rooms",     687},   L"687 Mercator"                         },
        {{L"rooms",     688},   L"688 Mercator"                         },
        {{L"rooms",     689},   L"689 Mercator"                         },
        {{L"rooms",     690},   L"690 Mercator"                         },
        {{L"rooms",     691},   L"691 Mercator"                         },
        {{L"rooms",     692},   L"692 Mercator"                         },
        {{L"rooms",     693},   L"693 Mercator"                         },
        {{L"rooms",     694},   L"694 Mercator old woman house. First floor"},
        {{L"rooms",     695},   L"695 Mercator, empty shop"             },
        {{L"rooms",     696},   L"696 Mercator, drug store"             },
        {{L"rooms",     697},   L"697 Mercator, variety shop"           },
        {{L"rooms",     698},   L"698 Mercator, shop's backroom"        },
        {{L"rooms",     699},   L"699 Mercator, church"                 },
        {{L"rooms",     700},   L"700 Mercator, church"                 },
        {{L"rooms",     701},   L"701 Mercator"                         },
        {{L"rooms",     702},   L"702 Mercator"                         },
        {{L"rooms",     703},   L"703 Mercator"                         },
        {{L"rooms",     704},   L"704 Mercator"                         },
        {{L"rooms",     705},   L"705 Mercator"                         },
        {{L"rooms",     706},   L"706 Mercator"                         },
        {{L"rooms",     707},   L"707 Madame yard's, corridor"          },
        {{L"rooms",     708},   L"708 Madame yard's"                    },
        {{L"rooms",     709},   L"709 Mercator, old woman's house first floor"},
        {{L"rooms",     710},   L"710 Madame yard's"                    },
        {{L"rooms",     711},   L"711 Verla, trap"                      },
        {{L"rooms",     712},   L"712 Verla"                            },
        {{L"rooms",     713},   L"713 Verla"                            },
        {{L"rooms",     714},   L"714 Verla"                            },
        {{L"rooms",     715},   L"715 Verla"                            },
        {{L"rooms",     716},   L"716 Verla"                            },
        {{L"rooms",     717},   L"717 Verla"                            },
        {{L"rooms",     718},   L"718 Verla"                            },
        {{L"rooms",     719},   L"719 Verla"                            },
        {{L"rooms",     720},   L"720 Verla"                            },
        {{L"rooms",     721},   L"721 Verla, church"                    },
        {{L"rooms",     722},   L"722 Verla"                            },
        {{L"rooms",     723},   L"723 Verla"                            },
        {{L"rooms",     724},   L"724 Verla"                            },
        {{L"rooms",     725},   L"725 Verla"                            },
        {{L"rooms",     726},   L"726 Destel"                           },
        {{L"rooms",     727},   L"727 Destel"                           },
        {{L"rooms",     728},   L"728 Destel"                           },
        {{L"rooms",     729},   L"729 Destel, inn first floor"          },
        {{L"rooms",     730},   L"730 Destel, inn second floor"         },
        {{L"rooms",     731},   L"731 Destel"                           },
        {{L"rooms",     732},   L"732 Destel"                           },
        {{L"rooms",     733},   L"733 Destel"                           },
        {{L"rooms",     734},   L"734 Destel"                           },
        {{L"rooms",     735},   L"735 Destel"                           },
        {{L"rooms",     736},   L"736 Destel, church"                   },
        {{L"rooms",     737},   L"737 Kazalt village"                   },
        {{L"rooms",     738},   L"738 Kazalt"                           },
        {{L"rooms",     739},   L"739 Kazalt"                           },
        {{L"rooms",     740},   L"740 Kazalt"                           },
        {{L"rooms",     741},   L"741 Kazalt"                           },
        {{L"rooms",     742},   L"742 Kazalt"                           },
        {{L"rooms",     743},   L"743 Kazalt"                           },
        {{L"rooms",     744},   L"744 Kazalt"                           },
        {{L"rooms",     745},   L"745 Kazalt, inn"                      },
        {{L"rooms",     746},   L"746 Kazalt, inn"                      },
        {{L"rooms",     747},   L"747 Kazalt, shop"                     },
        {{L"rooms",     748},   L"748 Kazalt"                           },
        {{L"rooms",     749},   L"749 Kazalt, church"                   },
        {{L"rooms",     750},   L"750 Mir's tower"                      },
        {{L"rooms",     751},   L"751 Mir's tower"                      },
        {{L"rooms",     752},   L"752 Mir's tower"                      },
        {{L"rooms",     753},   L"753 Mir's tower"                      },
        {{L"rooms",     754},   L"754 Mir's tower"                      },
        {{L"rooms",     755},   L"755 Mir's tower"                      },
        {{L"rooms",     756},   L"756 Mir's tower"                      },
        {{L"rooms",     757},   L"757 Mir's tower"                      },
        {{L"rooms",     758},   L"758 Mir's tower"                      },
        {{L"rooms",     759},   L"759 Mir's tower"                      },
        {{L"rooms",     760},   L"760 Mir's tower"                      },
        {{L"rooms",     761},   L"761 Mir's tower"                      },
        {{L"rooms",     762},   L"762 Mir's tower"                      },
        {{L"rooms",     763},   L"763 Mir's tower"                      },
        {{L"rooms",     764},   L"764 Mir's tower"                      },
        {{L"rooms",     765},   L"765 Mir's tower"                      },
        {{L"rooms",     766},   L"766 Mir's tower"                      },
        {{L"rooms",     767},   L"767 Mir's tower"                      },
        {{L"rooms",     768},   L"768 Mir's tower"                      },
        {{L"rooms",     769},   L"769 Mir's tower"                      },
        {{L"rooms",     770},   L"770 Mir's tower"                      },
        {{L"rooms",     771},   L"771 Mir's tower"                      },
        {{L"rooms",     772},   L"772 Mir's tower"                      },
        {{L"rooms",     773},   L"773 Mir's tower"                      },
        {{L"rooms",     774},   L"774 Mir's tower"                      },
        {{L"rooms",     775},   L"775 Mir's tower"                      },
        {{L"rooms",     776},   L"776 Mir's tower"                      },
        {{L"rooms",     777},   L"777 Mir's tower"                      },
        {{L"rooms",     778},   L"778 Mir's tower"                      },
        {{L"rooms",     779},   L"779 Mir's tower"                      },
        {{L"rooms",     780},   L"780 Mir's tower"                      },
        {{L"rooms",     781},   L"781 Mir's tower"                      },
        {{L"rooms",     782},   L"782 Mir's tower"                      },
        {{L"rooms",     783},   L"783 Mir's tower"                      },
        {{L"rooms",     784},   L"784 Mir's tower, Mir's lair"          },
        {{L"rooms",     785},   L"785 Helga's hut"                      },
        {{L"rooms",     786},   L"786 Helga's hut"                      },
        {{L"rooms",     787},   L"787 Helga's hut"                      },
        {{L"rooms",     788},   L"788 Helga's hut"                      },
        {{L"rooms",     789},   L"789 Helga's hut"                      },
        {{L"rooms",     790},   L"790 Helga's hut"                      },
        {{L"rooms",     791},   L"791 Helga's hut"                      },
        {{L"rooms",     792},   L"792 Helga's hut"                      },
        {{L"rooms",     793},   L"793 Helga's hut"                      },
        {{L"rooms",     794},   L"794 Helga's hut"                      },
        {{L"rooms",     795},   L"795 Helga's hut"                      },
        {{L"rooms",     796},   L"796 Helga's hut"                      },
        {{L"rooms",     797},   L"797 Helga's hut"                      },
        {{L"rooms",     798},   L"798 Helga's hut"                      },
        {{L"rooms",     799},   L"799 Helga's hut"                      },
        {{L"rooms",     800},   L"800 Helga's hut"                      },
        {{L"rooms",     801},   L"801 Helga's hut"                      },
        {{L"rooms",     802},   L"802 Helga's hut"                      },
        {{L"rooms",     803},   L"803 Massan cave"                      },
        {{L"rooms",     804},   L"804 Massan cave"                      },
        {{L"rooms",     805},   L"805 Massan cave"                      },
        {{L"rooms",     806},   L"806 Massan cave"                      },
        {{L"rooms",     807},   L"807 Massan cave"                      },
        {{L"rooms",     808},   L"808 Tibor"                            },
        {{L"rooms",     809},   L"809 Tibor"                            },
        {{L"rooms",     810},   L"810 Tibor"                            },
        {{L"rooms",     811},   L"811 Tibor"                            },
        {{L"rooms",     812},   L"812 Tibor"                            },
        {{L"rooms",     813},   L"813 Tibor"                            },
        {{L"rooms",     814},   L"814 Tibor"                            },
        {{L"rooms",     815},   L"815 Tibor"                            },
        {{L"bgms",      0},     L"[00] The Marquis' Invitation"         },
        {{L"bgms",      1},     L"[01] Premonition of Trouble"          },
        {{L"bgms",      2},     L"[02] Overworld"                       },
        {{L"bgms",      3},     L"[03] Bustling Street"                 },
        {{L"bgms",      4},     L"[04] Torchlight"                      },
        {{L"bgms",      5},     L"[05] Prayers to God"                  },
        {{L"bgms",      6},     L"[06] Gumi"                            },
        {{L"bgms",      7},     L"[07] Beneath the Mysterious Tree"     },
        {{L"bgms",      8},     L"[08] Overworld"                       },
        {{L"bgms",      9},     L"[09] The King's Chamber"              },
        {{L"bgms",      10},    L"[0A] Mysterious Island"               },
        {{L"bgms",      11},    L"[0B] The Death God's Invitation"      },
        {{L"bgms",      12},    L"[0C] Deserted Street Corner"          },
        {{L"bgms",      13},    L"[0D] Labrynth"                        },
        {{L"bgms",      14},    L"[0E] The Silence, the Darkness, and..."},
        {{L"bgms",      15},    L"[0F] Light of the Setting Sun"        },
        {{L"bgms",      16},    L"[10] Friday and a Soft Breeze"        },
        {{L"bgms",      17},    L"[11] Divine Guardian of the Maze"     },
        {{L"bgms",      18},    L"[12] Fade Out"                        },
        {{L"sounds",    0},     L"<00> <Null>"                          },
        {{L"sounds",    1},     L"<01> Bustling Street"                 },
        {{L"sounds",    2},     L"<02> Torchlight"                      },
        {{L"sounds",    3},     L"<03> Premonition of Trouble"          },
        {{L"sounds",    4},     L"<04> Fanfare 1"                       },
        {{L"sounds",    5},     L"<05> Receive Item"                    },
        {{L"sounds",    6},     L"<06> Rest"                            },
        {{L"sounds",    7},     L"<07> Save Game"                       },
        {{L"sounds",    8},     L"<08> Status Heal"                     },
        {{L"sounds",    9},     L"<09> Poisoned"                        },
        {{L"sounds",    10},    L"<0A> The Death God's Invitation"      },
        {{L"sounds",    11},    L"<0B> Duke's Fanfare"                  },
        {{L"sounds",    12},    L"<0C> Fanfare 2"                       },
        {{L"sounds",    13},    L"<0D> Einstein Whistle"                },
        {{L"sounds",    14},    L"<0E> Black Market"                    },
        {{L"sounds",    15},    L"<0F> Surprise"                        },
        {{L"sounds",    16},    L"<10> Title"                           },
        {{L"sounds",    17},    L"<11> Let's Go On An Adventure"        },
        {{L"sounds",    18},    L"<12> Treasure Hunter Lyle"            },
        {{L"sounds",    19},    L"<13> Seeking Treasure"                },
        {{L"sounds",    20},    L"<14> Deserted Street Corner"          },
        {{L"sounds",    21},    L"<15> Friday and a Soft Breeze"        },
        {{L"sounds",    22},    L"<16> Hey, It's Your Turn!"            },
        {{L"sounds",    27},    L"<1B> To The Great Adventurers"        },
        {{L"sounds",    29},    L"<1D> Beneath the Mysterious Tree"     },
        {{L"sounds",    31},    L"<1F> Urgent, Nigel!"                  },
        {{L"sounds",    33},    L"<21> Prayers To God"                  },
        {{L"sounds",    34},    L"<22> Light Of The Setting Sun"        },
        {{L"sounds",    35},    L"<23> Wicked God's Banquet"            },
        {{L"sounds",    36},    L"<24> Heh Heh, I Think I Will Disrupt This Good Cheer"},
        {{L"sounds",    37},    L"<25> The Marquis' Invitation"         },
        {{L"sounds",    38},    L"<26> The King's Chamber"              },
        {{L"sounds",    39},    L"<27> Mysterious Island"               },
        {{L"sounds",    40},    L"<28> Friday's Memory"                 },
        {{L"sounds",    41},    L"<29> Divine Guardian of the Maze"     },
        {{L"sounds",    42},    L"<2A> The Silence, the Darkness, and..."},
        {{L"sounds",    43},    L"<2B> Labrynth"                        },
        {{L"sounds",    44},    L"<2C> A Ballad For Princess Loria"     },
        {{L"sounds",    45},    L"<2D> A Ballad For Princess Loria (Loop)"},
        {{L"sounds",    46},    L"<2E> Pink Book"                       },
        {{L"sounds",    47},    L"<2F> Adventure Spirit"                },
        {{L"sounds",    65},    L"<41> Skeleton Talk"                   },
        {{L"sounds",    66},    L"<42> Cursor Move"                     },
        {{L"sounds",    67},    L"<43> Cursor Select"                   },
        {{L"sounds",    68},    L"<44> Error Buzz"                      },
        {{L"sounds",    69},    L"<45> Speaker Pitch 8"                 },
        {{L"sounds",    70},    L"<46> Speaker Pitch 7"                 },
        {{L"sounds",    71},    L"<47> Speaker Pitch 6"                 },
        {{L"sounds",    72},    L"<48> Speaker Pitch 5"                 },
        {{L"sounds",    73},    L"<49> Speaker Pitch 4"                 },
        {{L"sounds",    74},    L"<4A> Speaker Pitch 3"                 },
        {{L"sounds",    75},    L"<4B> Speaker Pitch 2"                 },
        {{L"sounds",    76},    L"<4C> Speaker Pitch 1"                 },
        {{L"sounds",    77},    L"<4D> Warp"                            },
        {{L"sounds",    78},    L"<4E> Drum"                            },
        {{L"sounds",    79},    L"<4F> Cymbal"                          },
        {{L"sounds",    80},    L"<50> Snare Drum"                      },
        {{L"sounds",    81},    L"<51> Sword Swing"                     },
        {{L"sounds",    82},    L"<52> Sword Hitting Stone"             },
        {{L"sounds",    83},    L"<53> Jump"                            },
        {{L"sounds",    84},    L"<54> Fall"                            },
        {{L"sounds",    85},    L"<55> Exit"                            },
        {{L"sounds",    86},    L"<56> Throw"                           },
        {{L"sounds",    87},    L"<57> Enemy Cry"                       },
        {{L"sounds",    88},    L"<58> Door Lock"                       },
        {{L"sounds",    89},    L"<59> Rumble"                          },
        {{L"sounds",    90},    L"<5A> Health Recover"                  },
        {{L"sounds",    91},    L"<5B> Dog Transform"                   },
        {{L"sounds",    92},    L"<5C> HP Absorb"                       },
        {{L"sounds",    93},    L"<5D> Land"                            },
        {{L"sounds",    94},    L"<5E> Climb"                           },
        {{L"sounds",    95},    L"<5F> Throw Alt"                       },
        {{L"sounds",    96},    L"<60> Bounce"                          },
        {{L"sounds",    97},    L"<61> Player Take Damage"              },
        {{L"sounds",    98},    L"<62> Player Drop Object Alt"          },
        {{L"sounds",    99},    L"<63> Player Drop Object"              },
        {{L"sounds",    100},   L"<64> Player Take Damage Alt"          },
        {{L"sounds",    101},   L"<65> Player Die"                      },
        {{L"sounds",    102},   L"<66> Enemy Die"                       },
        {{L"sounds",    103},   L"<67> Enemy Take Damage"               },
        {{L"sounds",    104},   L"<68> Open Menu"                       },
        {{L"sounds",    105},   L"<69> Pick Up Item"                    },
        {{L"sounds",    106},   L"<6A> Pick Up Gold"                    },
        {{L"sounds",    107},   L"<6B> Kazalt Warp"                     },
        {{L"sounds",    108},   L"<6C> Switch"                          },
        {{L"sounds",    109},   L"<6D> Explosion"                       },
        {{L"sounds",    110},   L"<6E> Thud"                            },
        {{L"sounds",    111},   L"<6F> Enemy Die Alt"                   },
        {{L"sounds",    112},   L"<70> Enemy Take Damage Alt"           },
        {{L"sounds",    113},   L"<71> Fireball 1"                      },
        {{L"sounds",    114},   L"<72> Fireball 2"                      },
        {{L"sounds",    115},   L"<73> Short Rumble"                    },
        {{L"sounds",    116},   L"<74> Permanent Switch"                },
        {{L"sounds",    117},   L"<75> Latch"                           },
        {{L"sounds",    118},   L"<76> Friday Magic"                    },
        {{L"sounds",    119},   L"<77> Slash 1"                         },
        {{L"sounds",    120},   L"<78> Slash 2"                         },
        {{L"sounds",    121},   L"<79> Mir Warp"                        },
        {{L"sounds",    122},   L"<7A> Poison"                          },
        {{L"sounds",    253},   L"<FD> Fade Out"                        },
        {{L"sounds",    254},   L"<FE> Stop"                            },
        {{L"sounds",    255},   L"<FF> Load From D0"                    },
        {{L"entities",  0},     L"Nigel"                                },
        {{L"entities",  1},     L"Old Man"                              },
        {{L"entities",  2},     L"Male Red Bear"                        },
        {{L"entities",  3},     L"Boy"                                  },
        {{L"entities",  4},     L"Orc 1"                                },
        {{L"entities",  5},     L"Orc 2"                                },
        {{L"entities",  6},     L"Orc 3"                                },
        {{L"entities",  7},     L"Worm 1"                               },
        {{L"entities",  8},     L"Worm 2"                               },
        {{L"entities",  9},     L"Worm 3"                               },
        {{L"entities",  10},    L"Moneybag"                             },
        {{L"entities",  11},    L"Man 1"                                },
        {{L"entities",  12},    L"Woman 1"                              },
        {{L"entities",  13},    L"Girl"                                 },
        {{L"entities",  14},    L"Dog"                                  },
        {{L"entities",  15},    L"Chicken"                              },
        {{L"entities",  16},    L"Priest"                               },
        {{L"entities",  17},    L"Vase"                                 },
        {{L"entities",  18},    L"Chest"                                },
        {{L"entities",  19},    L"Small Grey Ball"                      },
        {{L"entities",  20},    L"Large Grey Ball"                      },
        {{L"entities",  21},    L"Small Yellow Platform"                },
        {{L"entities",  22},    L"Crate"                                },
        {{L"entities",  23},    L"Ninja 1"                              },
        {{L"entities",  24},    L"Ninja 2"                              },
        {{L"entities",  25},    L"Ninja 3"                              },
        {{L"entities",  26},    L"Lizard 1"                             },
        {{L"entities",  27},    L"Lizard 2"                             },
        {{L"entities",  28},    L"Lizard 3"                             },
        {{L"entities",  29},    L"Knight 1"                             },
        {{L"entities",  30},    L"Knight 2"                             },
        {{L"entities",  31},    L"Knight 3"                             },
        {{L"entities",  32},    L"Ghost 1"                              },
        {{L"entities",  33},    L"Ghost 2"                              },
        {{L"entities",  34},    L"Ghost 3"                              },
        {{L"entities",  35},    L"Mummy 1"                              },
        {{L"entities",  36},    L"Mummy 2"                              },
        {{L"entities",  37},    L"Mummy 3"                              },
        {{L"entities",  38},    L"Unicorn 1"                            },
        {{L"entities",  39},    L"Unicorn 2"                            },
        {{L"entities",  40},    L"Unicorn 3"                            },
        {{L"entities",  41},    L"Skeleton 1"                           },
        {{L"entities",  42},    L"Skeleton 2"                           },
        {{L"entities",  43},    L"Skeleton 3"                           },
        {{L"entities",  44},    L"Mimic 1"                              },
        {{L"entities",  45},    L"Mimic 2"                              },
        {{L"entities",  46},    L"Mimic 3"                              },
        {{L"entities",  47},    L"Child Red Bear"                       },
        {{L"entities",  48},    L"Male Dwarf"                           },
        {{L"entities",  49},    L"Female Yellow Bear"                   },
        {{L"entities",  50},    L"Soldier"                              },
        {{L"entities",  51},    L"Madame Yard"                          },
        {{L"entities",  52},    L"Dexter"                               },
        {{L"entities",  53},    L"Raft"                                 },
        {{L"entities",  54},    L"Mushroom 1"                           },
        {{L"entities",  55},    L"Mushroom 2"                           },
        {{L"entities",  56},    L"Mushroom 3"                           },
        {{L"entities",  57},    L"Giant 1"                              },
        {{L"entities",  58},    L"Giant 2"                              },
        {{L"entities",  59},    L"Giant 3"                              },
        {{L"entities",  60},    L"Bubble 1"                             },
        {{L"entities",  61},    L"Bubble 2"                             },
        {{L"entities",  62},    L"Bubble 3"                             },
        {{L"entities",  63},    L"Old Lady"                             },
        {{L"entities",  64},    L"Male Yellow Bear"                     },
        {{L"entities",  65},    L"Child Yellow Bear"                    },
        {{L"entities",  66},    L"Fara stake"                           },
        {{L"entities",  67},    L"Praying Yellow Bear"                  },
        {{L"entities",  68},    L"Skeleton Statue 1"                    },
        {{L"entities",  69},    L"Praying Red Bear"                     },
        {{L"entities",  70},    L"Skeleton Statue 2"                    },
        {{L"entities",  71},    L"Female Red Bear"                      },
        {{L"entities",  72},    L"Female Dwarf"                         },
        {{L"entities",  73},    L"Small Grey Spiked Ball"               },
        {{L"entities",  74},    L"Large Grey Spiked Ball"               },
        {{L"entities",  75},    L"Sacred Tree"                          },
        {{L"entities",  76},    L"Large Wood Platform"                  },
        {{L"entities",  77},    L"Injured Dog"                          },
        {{L"entities",  78},    L"Dead Body"                            },
        {{L"entities",  79},    L"Woman 2"                              },
        {{L"entities",  80},    L"Man 2"                                },
        {{L"entities",  81},    L"Invisible Cube"                       },
        {{L"entities",  82},    L"Ink"                                  },
        {{L"entities",  83},    L"Large Concrete Block"                 },
        {{L"entities",  84},    L"Square Switch"                        },
        {{L"entities",  85},    L"Round Switch"                         },
        {{L"entities",  86},    L"Unused Small Yellow Platform"         },
        {{L"entities",  87},    L"Unused Small Grey Platform"           },
        {{L"entities",  88},    L"Unused Small Green Platform"          },
        {{L"entities",  89},    L"Small Thin Yellow Platform"           },
        {{L"entities",  90},    L"Small Thin Grey Platform"             },
        {{L"entities",  91},    L"Unused Small Thin Green Platform"     },
        {{L"entities",  92},    L"Unused Large Dark Platform"           },
        {{L"entities",  93},    L"Large Thin Grey Platform"             },
        {{L"entities",  94},    L"Unused Large Thin Green Platform"     },
        {{L"entities",  95},    L"Unused Large Thin Yellow Platform"    },
        {{L"entities",  96},    L"Item Box"                             },
        {{L"entities",  97},    L"Friday"                               },
        {{L"entities",  98},    L"Large Boulder"                        },
        {{L"entities",  99},    L"Nigel in Bed"                         },
        {{L"entities",  100},   L"Godess Statue"                        },
        {{L"entities",  101},   L"2-Way Signpost"                       },
        {{L"entities",  102},   L"3-Way Signpost"                       },
        {{L"entities",  103},   L"Gate S"                               },
        {{L"entities",  104},   L"Gate N"                               },
        {{L"entities",  105},   L"Kayla"                                },
        {{L"entities",  106},   L"Wally"                                },
        {{L"entities",  107},   L"Woman 3"                              },
        {{L"entities",  108},   L"Locked Door"                          },
        {{L"entities",  109},   L"Man in bed"                           },
        {{L"entities",  110},   L"Lord Arthur"                          },
        {{L"entities",  111},   L"Kayla in Bath"                        },
        {{L"entities",  112},   L"Duke"                                 },
        {{L"entities",  113},   L"Small Wood Platform"                  },
        {{L"entities",  114},   L"Small Thin Dark Grey Platform"        },
        {{L"entities",  115},   L"Yellow Old Man"                       },
        {{L"entities",  116},   L"Man with Blue Shirt"                  },
        {{L"entities",  117},   L"Chef"                                 },
        {{L"entities",  118},   L"Princess"                             },
        {{L"entities",  119},   L"Golem Statue 1"                       },
        {{L"entities",  120},   L"Mir Magic Barrier"                    },
        {{L"entities",  121},   L"Sailor"                               },
        {{L"entities",  122},   L"Pockets"                              },
        {{L"entities",  123},   L"Skeleton Priest"                      },
        {{L"entities",  124},   L"Mir"                                  },
        {{L"entities",  125},   L"Unused Bird 1"                        },
        {{L"entities",  126},   L"Unused Bird 2"                        },
        {{L"entities",  127},   L"Unused Bird 3"                        },
        {{L"entities",  128},   L"Moralis"                              },
        {{L"entities",  129},   L"Bubble 4"                             },
        {{L"entities",  130},   L"Bubble 5"                             },
        {{L"entities",  131},   L"Bubble 6"                             },
        {{L"entities",  132},   L"Gnome"                                },
        {{L"entities",  133},   L"Zak"                                  },
        {{L"entities",  134},   L"Mir Wall Barrier"                     },
        {{L"entities",  135},   L"Small Fireball"                       },
        {{L"entities",  136},   L"Reaper 1"                             },
        {{L"entities",  137},   L"Reaper 2"                             },
        {{L"entities",  138},   L"Unused Reaper 3"                      },
        {{L"entities",  139},   L"Golem Statue 2"                       },
        {{L"entities",  140},   L"Corrupted Round Switch"               },
        {{L"entities",  141},   L"Small Green Spiked Ball"              },
        {{L"entities",  142},   L"Large Grey Spiked Ball"               },
        {{L"entities",  143},   L"Ghost Generator 1"                    },
        {{L"entities",  144},   L"Ghost Generator 2"                    },
        {{L"entities",  145},   L"Ghost Generator 3"                    },
        {{L"entities",  146},   L"Golem 1"                              },
        {{L"entities",  147},   L"Golem 2"                              },
        {{L"entities",  148},   L"Golem 3"                              },
        {{L"entities",  149},   L"Spectre 1"                            },
        {{L"entities",  150},   L"Spectre 2"                            },
        {{L"entities",  151},   L"Spectre 3"                            },
        {{L"entities",  152},   L"Unused Small Blue Ball"               },
        {{L"entities",  153},   L"Small Red Ball"                       },
        {{L"entities",  154},   L"Unused Large Blue Ball"               },
        {{L"entities",  155},   L"Large Red Ball"                       },
        {{L"entities",  156},   L"Unused Magic Fox"                     },
        {{L"entities",  157},   L"Spinner 1"                            },
        {{L"entities",  158},   L"Duke Chair"                           },
        {{L"entities",  159},   L"Miro"                                 },
        {{L"entities",  160},   L"Ifrit"                                },
        {{L"entities",  161},   L"Ifrit Fireball"                       },
        {{L"entities",  162},   L"Gola"                                 },
        {{L"entities",  163},   L"Pink Golem Statue"                    },
        {{L"entities",  164},   L"Gold Golem Statue"                    },
        {{L"entities",  165},   L"Nole"                                 },
        {{L"entities",  166},   L"Nole Axe Projectile"                  },
        {{L"entities",  167},   L"Stone Warrior 1"                      },
        {{L"entities",  168},   L"Zak Boomerang"                        },
        {{L"entities",  169},   L"1-Way Signpost"                       },
        {{L"entities",  170},   L"Spinner 2"                            },
        {{L"entities",  171},   L"Stone Warrior 2"                      },
        {{L"entities",  172},   L"Gola Fireball"                        },
        {{L"entities",  173},   L"?AD"                                  },
        {{L"entities",  174},   L"?AE"                                  },
        {{L"entities",  175},   L"?AF"                                  },
        {{L"entities",  176},   L"?B0"                                  },
        {{L"entities",  177},   L"?B1"                                  },
        {{L"entities",  178},   L"?B2"                                  },
        {{L"entities",  179},   L"?B3"                                  },
        {{L"entities",  180},   L"?B4"                                  },
        {{L"entities",  181},   L"?B5"                                  },
        {{L"entities",  182},   L"?B6"                                  },
        {{L"entities",  183},   L"?B7"                                  },
        {{L"entities",  184},   L"?B8"                                  },
        {{L"entities",  185},   L"?B9"                                  },
        {{L"entities",  186},   L"?BA"                                  },
        {{L"entities",  187},   L"?BB"                                  },
        {{L"entities",  188},   L"?BC"                                  },
        {{L"entities",  189},   L"?BD"                                  },
        {{L"entities",  190},   L"?BE"                                  },
        {{L"entities",  191},   L"?BF"                                  },
        {{L"entities",  192},   L"EkeEke"                               },
        {{L"entities",  193},   L"Magic Sword"                          },
        {{L"entities",  194},   L"Ice Sword"                            },
        {{L"entities",  195},   L"Thunder Sword"                        },
        {{L"entities",  196},   L"Gaia Sword"                           },
        {{L"entities",  197},   L"Fireproof"                            },
        {{L"entities",  198},   L"Iron Boots"                           },
        {{L"entities",  199},   L"Healing Boots"                        },
        {{L"entities",  200},   L"Snow Spikes"                          },
        {{L"entities",  201},   L"Steel Breast"                         },
        {{L"entities",  202},   L"Chrome Breast"                        },
        {{L"entities",  203},   L"Shell Breast"                         },
        {{L"entities",  204},   L"Hyper Breast"                         },
        {{L"entities",  205},   L"Mars Stone"                           },
        {{L"entities",  206},   L"Moon Stone"                           },
        {{L"entities",  207},   L"Saturn Stone"                         },
        {{L"entities",  208},   L"Venus Stone"                          },
        {{L"entities",  209},   L"Awakening Book"                       },
        {{L"entities",  210},   L"Detox Grass"                          },
        {{L"entities",  211},   L"Gaia Statue"                          },
        {{L"entities",  212},   L"Golden Statue"                        },
        {{L"entities",  213},   L"Mind Repair"                          },
        {{L"entities",  214},   L"Casino Ticket"                        },
        {{L"entities",  215},   L"Axe Magic"                            },
        {{L"entities",  216},   L"Blue Ribbon"                          },
        {{L"entities",  217},   L"Buyer Card"                           },
        {{L"entities",  218},   L"Lantern"                              },
        {{L"entities",  219},   L"Garlic"                               },
        {{L"entities",  220},   L"Anti-Paralyze"                        },
        {{L"entities",  221},   L"Statue of Jypta"                      },
        {{L"entities",  222},   L"Sun Stone"                            },
        {{L"entities",  223},   L"Armlet"                               },
        {{L"entities",  224},   L"Einstein Whistle"                     },
        {{L"entities",  225},   L"Detox Book"                           },
        {{L"entities",  226},   L"AntiCurse"                            },
        {{L"entities",  227},   L"Record Book"                          },
        {{L"entities",  228},   L"Spell Book"                           },
        {{L"entities",  229},   L"Hotel Register"                       },
        {{L"entities",  230},   L"Island Map"                           },
        {{L"entities",  231},   L"Lithograph"                           },
        {{L"entities",  232},   L"Red Jewel"                            },
        {{L"entities",  233},   L"Pawn Ticket"                          },
        {{L"entities",  234},   L"Purple Jewel"                         },
        {{L"entities",  235},   L"Gola's Eye"                           },
        {{L"entities",  236},   L"Death Statue"                         },
        {{L"entities",  237},   L"Dahl"                                 },
        {{L"entities",  238},   L"Restoration"                          },
        {{L"entities",  239},   L"Logs"                                 },
        {{L"entities",  240},   L"Oracle Stone"                         },
        {{L"entities",  241},   L"Idol Stone"                           },
        {{L"entities",  242},   L"Key"                                  },
        {{L"entities",  243},   L"Safety Pass"                          },
        {{L"entities",  244},   L"No52"                                 },
        {{L"entities",  245},   L"Bell"                                 },
        {{L"entities",  246},   L"Shortcake"                            },
        {{L"entities",  247},   L"Gola's Nail"                          },
        {{L"entities",  248},   L"Gola's Horn"                          },
        {{L"entities",  249},   L"Gola's Fang"                          },
        {{L"entities",  250},   L"Broad Sword"                          },
        {{L"entities",  251},   L"Leather Breast"                       },
        {{L"entities",  252},   L"Leather Boots"                        },
        {{L"entities",  253},   L"None"                                 },
        {{L"entities",  254},   L"Lifestock"                            },
        {{L"entities",  255},   L"No63"                                 },
    };
}
